<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'QA',
  'author' => 'DX',
  'description' => 'HandALM_HQA',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'HandALM_HQA',
  'published_date' => '2016-05-19 02:53:37',
  'type' => 'module',
  'version' => 1463626418,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'HandALM_HQA',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'QA_CollectionElement',
      'class' => 'QA_CollectionElement',
      'path' => 'modules/QA_CollectionElement/QA_CollectionElement.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'QA_CollectionPlan',
      'class' => 'QA_CollectionPlan',
      'path' => 'modules/QA_CollectionPlan/QA_CollectionPlan.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'QA_CollectionPlanDefine',
      'class' => 'QA_CollectionPlanDefine',
      'path' => 'modules/QA_CollectionPlanDefine/QA_CollectionPlanDefine.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'QA_ElementType',
      'class' => 'QA_ElementType',
      'path' => 'modules/QA_ElementType/QA_ElementType.php',
      'tab' => true,
    ),
    4 => 
    array (
      'module' => 'QA_inputresult',
      'class' => 'QA_inputresult',
      'path' => 'modules/QA_inputresult/QA_inputresult.php',
      'tab' => true,
    ),
    5 => 
    array (
      'module' => 'QA_PlanType',
      'class' => 'QA_PlanType',
      'path' => 'modules/QA_PlanType/QA_PlanType.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/qa_collectionelement_haa_uom_HAA_UOM.php',
      'to_module' => 'HAA_UOM',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/qa_collectionelement_qa_elementtype_QA_ElementType.php',
      'to_module' => 'QA_ElementType',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/qa_collectionplan_haa_uom_HAA_UOM.php',
      'to_module' => 'HAA_UOM',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/qa_collectionplan_qa_collectionelement_QA_CollectionElement.php',
      'to_module' => 'QA_CollectionElement',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/qa_collectionplan_qa_collectionplandefine_QA_CollectionPlanDefine.php',
      'to_module' => 'QA_CollectionPlanDefine',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/qa_collectionplan_qa_plantype_QA_PlanType.php',
      'to_module' => 'QA_PlanType',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/qa_inputresult_qa_collectionplan_QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/qa_collectionelement_haa_uomMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/qa_collectionelement_qa_elementtypeMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/qa_collectionplan_haa_uomMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/qa_collectionplan_qa_collectionelementMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/qa_collectionplan_qa_collectionplandefineMetaData.php',
    ),
    5 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/qa_collectionplan_qa_plantypeMetaData.php',
    ),
    6 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/qa_inputresult_qa_collectionplanMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/QA_CollectionElement',
      'to' => 'modules/QA_CollectionElement',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/QA_CollectionPlan',
      'to' => 'modules/QA_CollectionPlan',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/QA_CollectionPlanDefine',
      'to' => 'modules/QA_CollectionPlanDefine',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/QA_ElementType',
      'to' => 'modules/QA_ElementType',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/QA_inputresult',
      'to' => 'modules/QA_inputresult',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/QA_PlanType',
      'to' => 'modules/QA_PlanType',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionElement.php',
      'to_module' => 'QA_CollectionElement',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionElement.php',
      'to_module' => 'QA_CollectionElement',
      'language' => 'zh_CN',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionElement.php',
      'to_module' => 'QA_CollectionElement',
      'language' => 'zh_TW',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/HAA_UOM.php',
      'to_module' => 'HAA_UOM',
      'language' => 'en_us',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/HAA_UOM.php',
      'to_module' => 'HAA_UOM',
      'language' => 'zh_CN',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/HAA_UOM.php',
      'to_module' => 'HAA_UOM',
      'language' => 'zh_TW',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionElement.php',
      'to_module' => 'QA_CollectionElement',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionElement.php',
      'to_module' => 'QA_CollectionElement',
      'language' => 'zh_CN',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionElement.php',
      'to_module' => 'QA_CollectionElement',
      'language' => 'zh_TW',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_ElementType.php',
      'to_module' => 'QA_ElementType',
      'language' => 'en_us',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_ElementType.php',
      'to_module' => 'QA_ElementType',
      'language' => 'zh_CN',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_ElementType.php',
      'to_module' => 'QA_ElementType',
      'language' => 'zh_TW',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
      'language' => 'zh_CN',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
      'language' => 'zh_TW',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/HAA_UOM.php',
      'to_module' => 'HAA_UOM',
      'language' => 'en_us',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/HAA_UOM.php',
      'to_module' => 'HAA_UOM',
      'language' => 'zh_CN',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/HAA_UOM.php',
      'to_module' => 'HAA_UOM',
      'language' => 'zh_TW',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
      'language' => 'en_us',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
      'language' => 'zh_CN',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
      'language' => 'zh_TW',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionElement.php',
      'to_module' => 'QA_CollectionElement',
      'language' => 'en_us',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionElement.php',
      'to_module' => 'QA_CollectionElement',
      'language' => 'zh_CN',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionElement.php',
      'to_module' => 'QA_CollectionElement',
      'language' => 'zh_TW',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
      'language' => 'en_us',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
      'language' => 'zh_CN',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
      'language' => 'zh_TW',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionPlanDefine.php',
      'to_module' => 'QA_CollectionPlanDefine',
      'language' => 'en_us',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionPlanDefine.php',
      'to_module' => 'QA_CollectionPlanDefine',
      'language' => 'zh_CN',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionPlanDefine.php',
      'to_module' => 'QA_CollectionPlanDefine',
      'language' => 'zh_TW',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
      'language' => 'en_us',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
      'language' => 'zh_CN',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
      'language' => 'zh_TW',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_PlanType.php',
      'to_module' => 'QA_PlanType',
      'language' => 'en_us',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_PlanType.php',
      'to_module' => 'QA_PlanType',
      'language' => 'zh_CN',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_PlanType.php',
      'to_module' => 'QA_PlanType',
      'language' => 'zh_TW',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_inputresult.php',
      'to_module' => 'QA_inputresult',
      'language' => 'en_us',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_inputresult.php',
      'to_module' => 'QA_inputresult',
      'language' => 'zh_CN',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_inputresult.php',
      'to_module' => 'QA_inputresult',
      'language' => 'zh_TW',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
      'language' => 'en_us',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
      'language' => 'zh_CN',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
      'language' => 'zh_TW',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/zh_CN.lang.php',
      'to_module' => 'application',
      'language' => 'zh_CN',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/qa_collectionelement_haa_uom_QA_CollectionElement.php',
      'to_module' => 'QA_CollectionElement',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/qa_collectionelement_haa_uom_HAA_UOM.php',
      'to_module' => 'HAA_UOM',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/qa_collectionelement_qa_elementtype_QA_CollectionElement.php',
      'to_module' => 'QA_CollectionElement',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/qa_collectionelement_qa_elementtype_QA_ElementType.php',
      'to_module' => 'QA_ElementType',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/qa_collectionplan_haa_uom_QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/qa_collectionplan_haa_uom_HAA_UOM.php',
      'to_module' => 'HAA_UOM',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/qa_collectionplan_qa_collectionelement_QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/qa_collectionplan_qa_collectionelement_QA_CollectionElement.php',
      'to_module' => 'QA_CollectionElement',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/qa_collectionplan_qa_collectionplandefine_QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/qa_collectionplan_qa_collectionplandefine_QA_CollectionPlanDefine.php',
      'to_module' => 'QA_CollectionPlanDefine',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/qa_collectionplan_qa_plantype_QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/qa_collectionplan_qa_plantype_QA_PlanType.php',
      'to_module' => 'QA_PlanType',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/qa_inputresult_qa_collectionplan_QA_inputresult.php',
      'to_module' => 'QA_inputresult',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/qa_inputresult_qa_collectionplan_QA_CollectionPlan.php',
      'to_module' => 'QA_CollectionPlan',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    3 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    4 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    5 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    6 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);