<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/

$dictionary['HAT_Incidents'] = array(
	'table'=>'hat_incidents',
	'audited'=>true,
    'inline_edit'=>true,
    'duplicate_merge'=>true,
    'fields'=>array (
      'haa_frameworks_id_c' => 
      array (
        'required' => false,
        'name' => 'haa_frameworks_id_c',
        'vname' => 'LBL_FRAMEWORKS_HAA_FRAMEWORKS_ID',
        'type' => 'id',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => 0,
        'audited' => false,
        'inline_edit' => true,
        'reportable' => false,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => 36,
        'size' => '20',
        ),
      'frameworks' => 
      array (
        'required' => true,
        'source' => 'non-db',
        'name' => 'frameworks',
        'vname' => 'LBL_FRAMEWORKS',
        'type' => 'relate',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        'id_name' => 'haa_frameworks_id_c',
        'ext2' => 'HAA_Frameworks',
        'module' => 'HAA_Frameworks',
        'rname' => 'name',
        'quicksearch' => 'enabled',
        'studio' => 'visible',
        ),
      'hat_eventtype_id_c' => 
      array (
        'required' => false,
        'name' => 'hat_eventtype_id_c',
        'vname' => 'LBL_EVENT_TYPE_HAT_EVENTTYPE_ID',
        'type' => 'id',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => 0,
        'audited' => false,
        'inline_edit' => true,
        'reportable' => false,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => 36,
        'size' => '20',
        ),
      'event_type' => 
      array (
        'required' => true,
        'source' => 'non-db',
        'name' => 'event_type',
        'vname' => 'LBL_EVENT_TYPE',
        'type' => 'relate',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        'id_name' => 'hat_eventtype_id_c',
        'ext2' => 'HAT_EventType',
        'module' => 'HAT_EventType',
        'rname' => 'name',
        'quicksearch' => 'enabled',
        'studio' => 'visible',
        ),
      'hat_eventtype_id1_c' => 
      array (
        'required' => false,
        'name' => 'hat_eventtype_id1_c',
        'vname' => 'LBL_EVENT_SUBTYPE_HAT_EVENTTYPE_ID',
        'type' => 'id',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => 0,
        'audited' => false,
        'inline_edit' => true,
        'reportable' => false,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => 36,
        'size' => '20',
        ),
      'event_subtype' => 
      array (
        'required' => false,
        'source' => 'non-db',
        'name' => 'event_subtype',
        'vname' => 'LBL_EVENT_SUBTYPE',
        'type' => 'relate',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        'id_name' => 'hat_eventtype_id1_c',
        'ext2' => 'HAT_EventType',
        'module' => 'HAT_EventType',
        'rname' => 'name',
        'quicksearch' => 'enabled',
        'studio' => 'visible',
        ),
      'hat_assets_id_c' => 
      array (
        'required' => false,
        'name' => 'hat_assets_id_c',
        'vname' => 'LBL_ASSET_NUMBER_HAT_ASSETS_ID',
        'type' => 'id',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => 0,
        'audited' => false,
        'inline_edit' => true,
        'reportable' => false,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => 36,
        'size' => '20',
        ),
      'asset_number' => 
      array (
        'required' => true,
        'source' => 'non-db',
        'name' => 'asset_number',
        'vname' => 'LBL_ASSET_NUMBER',
        'type' => 'relate',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        'id_name' => 'hat_assets_id_c',
        'ext2' => 'HAT_Assets',
        'module' => 'HAT_Assets',
        'rname' => 'asset_number',
        'quicksearch' => 'enabled',
        'studio' => 'visible',
        ),
      'asset_name' => 
      array (
          'name' => 'asset_name',
          'vname' => 'LBL_ASSET_NAME',
          'type' => 'varchar',
          'len' => '240',
          'source' => 'non-db',
          'studio' => 'visible',
          ),
      'contact_id_c' => 
      array (
        'required' => false,
        'name' => 'contact_id_c',
        'vname' => 'LBL_PERSON_NUMBER_CONTACT_ID',
        'type' => 'id',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => 0,
        'audited' => false,
        'inline_edit' => true,
        'reportable' => false,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => 36,
        'size' => '20',
        ),
      'person_number' => 
      array (
        'required' => false,
        'source' => 'non-db',
        'name' => 'person_number',
        'vname' => 'LBL_PERSON_NUMBER',
        'type' => 'relate',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        'id_name' => 'contact_id_c',
        'ext2' => 'Contacts',
        'module' => 'Contacts',
        'rname' => 'employee_number_c',
        'quicksearch' => 'enabled',
        'studio' => 'visible',
        ),
      'person_name' => 
      array (
          'name' => 'person_name',
          'vname' => 'LBL_PERSON_NAME',
          'type' => 'varchar',
          'len' => '240',
          'source' => 'non-db',
          'studio' => 'visible',
          ),
      'event_object' => 
      array (
        'required' => false,
        'name' => 'event_object',
        'vname' => 'LBL_EVENT_OBJECT',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        ),
      'event_resp_party' => 
      array (
        'required' => false,
        'name' => 'event_resp_party',
        'vname' => 'LBL_EVENT_RESP_PARTY',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        ),
      'event_date' => 
      array (
        'required' => true,
        'name' => 'event_date',
        'vname' => 'LBL_EVENT_DATE',
        'type' => 'datetimecombo',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'size' => '20',
        'enable_range_search' => false,
        'dbType' => 'datetime',
        'display_default' => 'now&09:00am',
        ),
      'event_location' => 
      array (
        'required' => true,
        'name' => 'event_location',
        'vname' => 'LBL_EVENT_LOCATION',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        ),
      'name' => 
      array (
        'name' => 'name',
        'vname' => 'LBL_NAME',
        'type' => 'name',
        'link' => true,
        'dbType' => 'varchar',
        'len' => '255',
        'unified_search' => false,
        'full_text_search' => 
        array (
          'boost' => 3,
          ),
        'required' => true,
        'importable' => 'required',
        'duplicate_merge' => 'disabled',
        'merge_filter' => 'disabled',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'size' => '20',
        ),
      'fine' => 
      array (
        'required' => false,
        'name' => 'fine',
        'vname' => 'LBL_FINE',
        'type' => 'float',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '18',
        'size' => '20',
        'enable_range_search' => false,
        'precision' => '2',
        ),
      'treatment_process' => 
      array (
        'required' => false,
        'name' => 'treatment_process',
        'vname' => 'LBL_TREATMENT_PROCESS',
        'type' => 'text',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'size' => '20',
        'studio' => 'visible',
        'rows' => '4',
        'cols' => '20',
        ),
      'description' => 
      array (
        'name' => 'description',
        'vname' => 'LBL_DESCRIPTION',
        'type' => 'text',
        'comment' => 'Full text of the note',
        'rows' => '6',
        'cols' => '80',
        'required' => false,
        'massupdate' => 0,
        'no_default' => false,
        'comments' => 'Full text of the note',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'size' => '20',
        'studio' => 'visible',
        ),
      'treatment_status' => 
      array (
        'required' => true,
        'name' => 'treatment_status',
        'vname' => 'LBL_TREATMENT_STATUS',
        'type' => 'enum',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => 100,
        'size' => '20',
        'options' => 'hat_treatment_status_list',
        'studio' => 'visible',
        'dependency' => false,
        ),
      'attribute1' => 
      array (
        'required' => false,
        'name' => 'attribute1',
        'vname' => 'LBL_ATTRIBUTE1',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        ),
      'attribute2' => 
      array (
        'required' => false,
        'name' => 'attribute2',
        'vname' => 'LBL_ATTRIBUTE2',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        ),
      'attribute3' => 
      array (
        'required' => false,
        'name' => 'attribute3',
        'vname' => 'LBL_ATTRIBUTE3',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        ),
      'attribute4' => 
      array (
        'required' => false,
        'name' => 'attribute4',
        'vname' => 'LBL_ATTRIBUTE4',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        ),
      'attribute5' => 
      array (
        'required' => false,
        'name' => 'attribute5',
        'vname' => 'LBL_ATTRIBUTE5',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        ),
      'attribute6' => 
      array (
        'required' => false,
        'name' => 'attribute6',
        'vname' => 'LBL_ATTRIBUTE6',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        ),
      'attribute7' => 
      array (
        'required' => false,
        'name' => 'attribute7',
        'vname' => 'LBL_ATTRIBUTE7',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        ),
      'attribute8' => 
      array (
        'required' => false,
        'name' => 'attribute8',
        'vname' => 'LBL_ATTRIBUTE8',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        ),
      'event_number' => 
      array (
        'required' => true,
        'name' => 'event_number',
        'vname' => 'LBL_EVENT_NUMBER',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        ),
      'haos_revenues_quotes_id' => 
      array (
        'required' => false,
        'name' => 'haos_revenues_quotes_id',
        'vname' => 'LBL_HAOS_REVENUES_QUOTES_ID',
        'type' => 'id',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => 0,
        'audited' => false,
        'inline_edit' => true,
        'reportable' => false,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => 36,
        'size' => '20',
        ),
      'revenue_quote_number' => 
      array (
        'required' => false,
        'source' => 'non-db',
        'name' => 'revenue_quote_number',
        'vname' => 'LBL_REVENUE_QUOTE_NUMBER',
        'type' => 'relate',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        'id_name' => 'haos_revenues_quotes_id',
        'ext2' => 'HAOS_Revenues_Quotes',
        'module' => 'HAOS_Revenues_Quotes', 
        'rname' => 'revenue_quote_number',
        'quicksearch' => 'enabled',
        'studio' => 'visible',
        ),
      'cleared_status' => 
      array (
          'name' => 'cleared_status',
          'vname' => 'LBL_CLEARED_STATUS',
          'type' => 'varchar',
          'len' => '240',
          'source' => 'non-db',
          'studio' => 'visible',
          ),
      'clear_status' => 
      array (
          'name' => 'clear_status',
          'vname' => 'LBL_CLEAR_STATUS',
          'type' => 'varchar',
          'len' => '240',
          'source' => 'non-db',
          'studio' => 'visible',
          ),
      'invoice_number' => 
      array (
          'name' => 'invoice_number',
          'vname' => 'LBL_INVOICE_NUMBER',
          'type' => 'varchar',
          'len' => '240',
          'source' => 'non-db',
          'studio' => 'visible',
          ),
      ),
'relationships'=>array (
    ),
'optimistic_locking'=>true,
'unified_search'=>true,
);
if (!class_exists('VardefManager')){
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('HAT_Incidents','HAT_Incidents', array('basic','assignable','security_groups'));
