<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/

$dictionary['HIT_Racks'] = array(
	'table'=>'hit_racks',
	'audited'=>true,
	'inline_edit'=>true,
	'duplicate_merge'=>true,
	'fields'=>array (
		'asset_number' => 
		array (
			'required' => true,
			'source' => 'non-db',
			'name' => 'asset_number',
			'vname' => 'LBL_ASSET',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'studio' => 'visible',
			),
		'hat_assets_id' => 
		array (
			'required' => false,
			'name' => 'hat_assets_id',
			'vname' => 'LBL_HAT_ASSETS_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'asset' => 
		array (
			'required' => true,
			'source' => 'non-db',
			'name' => 'asset',
			'vname' => 'LBL_ASSET',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'hat_assets_id',
			'ext2' => 'HAT_Assets',
			'module' => 'HAT_Assets',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'asset_desc' => 
		array (
			'name' => 'asset_desc',
			'type' => 'vchar',
			'vname' => 'LBL_ASSET_DESC',
			'module' => 'HAT_Assets',
			'source' => 'non-db',
			'dbType' => 'non-db',
			'studio' => 'visible',
			),
		'occupation' => 
		array (
			'name' => 'occupation',
			'type' => 'vchar',
			'vname' => 'LBL_OCCUPATION',
			'source' => 'non-db',
			'dbType' => 'non-db',
			'studio' => 'visible',
			),
		'asset_status' =>
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'asset_status',
			'vname' => 'LBL_ASSET_STATUS',
			'type' => 'enum',
			'massupdate' => '1',
			'default' => 'InService',
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 100,
			'size' => '20',
			'options' => 'asset_status_list',
			'studio' => 'visible',
			'dependency' => false,
			),
		'supplier_desc' =>
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'supplier_desc',
			'vname' => 'LBL_USING_PERSON_DESC',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => false,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			),
		'using_person_desc' =>
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'using_person_desc',
			'vname' => 'LBL_USING_PERSON_DESC',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => false,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			),
		'owning_person_desc' =>
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'owning_person_desc',
			'vname' => 'LBL_OWNING_PERSON_DESC',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => false,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			),
		'using_person_id' =>
		array (
			'required' => false,
			'name' => 'using_person_id',
			'vname' => 'LBL_USING_PERSON_ID',
			'type' => 'varchar',
			'source' => 'non-db',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'using_person' =>
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'using_person',
			'vname' => 'LBL_USING_PERSON',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => false,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'using_person_id',
			'ext2' => 'Contacts',
			'module' => 'Contacts',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'owning_person_id' =>
		array (
			'required' => false,
			'name' => 'owning_person_id',
			'vname' => 'LBL_OWNING_PERSON_ID',
			'type' => 'varchar',
			'source' => 'non-db',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'owning_person' =>
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'owning_person',
			'vname' => 'LBL_OWNING_PERSON',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'owning_person_id',
			'ext2' => 'Contacts',
			'module' => 'Contacts',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'using_org_id' =>
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'using_org_id',
			'vname' => 'LBL_USING_ORG_ID',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'using_org' =>
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'using_org',
			'vname' => 'LBL_USING_ORG',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'using_org_id',
			'ext2' => 'Accounts',
			'module' => 'Accounts',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'owning_org_id' =>
		array (
			'required' => false,
			'name' => 'owning_org_id',
			'vname' => 'LBL_OWING_ORG_ID',
			'source' => 'non-db',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'owning_org' =>
		array (
			'required' => true,
			'source' => 'non-db',
			'name' => 'owning_org',
			'vname' => 'LBL_OWING_ORG',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'owning_org_id',
			'ext2' => 'Accounts',
			'module' => 'Accounts',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'asset_location' =>
		array (
			'required' => true,
			'source' => 'non-db',
			'name' => 'asset_location',
			'vname' => 'LBL_ASSET_LOCATION',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'asset_location_id',
			'ext2' => 'HAT_Asset_Locations',
			'module' => 'HAT_Asset_Locations',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'asset_location_id' =>
		array (
			'required' => false,
			'name' => 'asset_location_id',
			'vname' => 'LBL_ASSET_LOCATION_ID',
			'type' => 'varchar',
			'source' => 'non-db',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'height' => 
		array (
			'required' => true,
			'name' => 'height',
			'vname' => 'LBL_HEIGHT',
			'type' => 'int',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => '',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'enable_range_search' => false,
			'disable_num_format' => '',
			'min' => false,
			'max' => false,
			),
		'dimension_external' => 
		array (
			'required' => false,
			'name' => 'dimension_external',
			'vname' => 'LBL_DIMENSION_EXTERNAL',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => '',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'enable_range_search' => false,
			'disable_num_format' => '',
			'min' => false,
			'max' => false,
			),
		'dimension_internal' => 
		array (
			'required' => false,
			'name' => 'dimension_internal',
			'vname' => 'LBL_DIMENSION_INTERNAL',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => '',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'enable_range_search' => false,
			'disable_num_format' => '',
			'min' => false,
			'max' => false,
			),
		'rated_current' => 
		array (
			'required' => false,
			'name' => 'rated_current',
			'vname' => 'LBL_RATED_CURRENT',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => '',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'enable_range_search' => false,
			'disable_num_format' => '',
			'min' => false,
			'max' => false,
			),
		'standard_power' => 
		array (
			'required' => false,
			'name' => 'standard_power',
			'vname' => 'LBL_STANDARD_POWER',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => '',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'enable_range_search' => false,
			'disable_num_format' => '',
			'min' => false,
			'max' => false,
			),

		'stock_number' => 
		array (
			'required' => false,
			'name' => 'stock_number',
			'vname' => 'LBL_STOCK_NUMBER',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => '',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'enable_range_search' => false,
			'disable_num_format' => '',
			'min' => false,
			'max' => false,
			),		
		'numbering_rule' => 
		array (
			'required' => true,
			'name' => 'numbering_rule',
			'vname' => 'LBL_NUMBERING_RULE',
			'type' => 'enum',
			'massupdate' => 0,
			'default' => 'BOTTOM',
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 100,
			'size' => '20',
			'options' => 'hit_racks_numbering_list',
			'studio' => 'visible',
			'dependency' => false,
			),
		'haa_frameworks_id' =>
		array (
			'required' => false,
			'name' => 'haa_frameworks_id',
			'vname' => 'LBL_FRAMEWORK_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'framework' =>
		array (
			'required' => true,
			'source' => 'non-db',
			'name' => 'framework',
			'vname' => 'LBL_FRAMEWORK',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'haa_frameworks_id',
			'ext2' => 'HAA_Frameworks',
			'module' => 'HAA_Frameworks',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'start_date' =>
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'start_date',
			'vname' => 'LBL_START_DATE',
			'type' => 'date',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'size' => '20',
			'enable_range_search' => false,
			),
		'asset_source_type' =>
		array (
			'source' => 'non-db',    	
			'required' => true,
			'name' => 'asset_source_type',
			'vname' => 'LBL_SOURCE_TYPE',
			'type' => 'enum',
			'massupdate' => '1',
			'default' => 'PURCHASE',
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 100,
			'size' => '20',
			'options' => 'hat_asset_source_type_list',
			'studio' => 'visible',
			'dependency' => false,
			),
		'asset_source_ref' =>
		array (
			'source' => 'non-db',    	
			'required' => false,
			'name' => 'asset_source_ref',
			'vname' => 'LBL_SOURCE_REF',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			),
    'supplier_org_id' =>
    array (
      'inline_edit' => 1,
      'required' => false,
     // 'source' => 'custom_fields',
      'name' => 'supplier_org_id',
      'vname' => 'LBL_SUPPLIER_ORG_ID',
      'source' => 'non-db',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'HAT_Assetssupplier_id',
      //'custom_module' => 'HAT_Assets',
      ),
    'supplier_org' =>
    array (
      'inline_edit' => '1',
      'labelValue' => 'Supplier/Provider',
      'required' => false,
      'source' => 'non-db',
      'name' => 'supplier_org',
      'vname' => 'LBL_SUPPLIER_ORG',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'supplier_org_id',
      'ext2' => 'Accounts',
      'module' => 'Accounts',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      'id' => 'HAT_Assetssupplier',
      //'custom_module' => 'HAT_Assets',
      ),		
    'aos_products_id' =>
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'non-db',
      'name' => 'aos_products_id',
      'vname' => 'LBL_ASSET_GROUP_AOS_PRODUCTS_ID',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'HAT_Assetsaos_products_id',
      //'custom_module' => 'HAT_Assets',
      ),
    'asset_group' =>
    array (
      'inline_edit' => '1',
      'labelValue' => 'Product/Asset Group',
      'required' => true,
      'source' => 'non-db',
      'name' => 'asset_group',
      'vname' => 'LBL_ASSET_GROUP',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'aos_products_id',
      'ext2' => 'AOS_Products',
      'module' => 'AOS_Products',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      'id' => 'HAT_Assetsaos_products_id',
      //'custom_module' => 'HAT_Assets',
      ),		
		'asset_source_details' =>
		array (
			'source' => 'non-db',    	
			'required' => false,
			'name' => 'asset_source_details',
			'vname' => 'LBL_SOURCE_DETAILS',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			),
		'asset_source' =>
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'asset_source',
			'vname' => 'LBL_ASSET_SOURCE',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'asset_source_id',
			'ext2' => 'HAT_Asset_Sources',
			'module' => 'HAT_Asset_Sources',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'asset_source_id' =>
		array (
			'required' => false,
			'name' => 'asset_source_id',
			'vname' => 'LBL_ASSET_SOURCE_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'enable_partial_allocation' =>
		array (
			'required' => false,
			'name' => 'enable_partial_allocation',
			'vname' => 'LBL_ENABLE_PARTIAL_ALLOCATION',
			'type' => 'bool',
			'massupdate' => 0,
			'default' => '1',
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			),        
		'position_display_area' =>
		array (
			'name' => 'position_display_area',
			'vname' => 'LBL_POSITION_DISPLAY_AREA',
			'source' => 'non-db',
			'type' => 'varchar',
			'massupdate' => 0,
			),
		'asset_link' =>
		array(
			'name' => 'asset_link',
			'type' => 'link',
			'relationship' => 'hit_racks_hat_assets',
			'vname' => 'LBL_CURRENT_ASSET_SUBPANEL_TITLE',
			'link_type' => 'many',
			'module' => 'HAT_Assets',
			'bean_name' => 'HAT_Assets',
			'source' => 'non-db',
			),
		'rack_allocation_link' =>
		array(
			'name' => 'asset_allocation_link',
			'type' => 'link',
			'relationship' => 'hit_rack_allocations_hit_racks',
			'vname' => 'LBL_CURRENT_ASSET_ALLOCATION_SUBPANEL_TITLE',
			'link_type' => 'many',
			'module' => 'HAT_Assets',
			'bean_name' => 'HAT_Assets',
			'source' => 'non-db',
			),

		),
'relationships'=>array (
	'hit_racks_hat_assets' => 
	array (
		'lhs_module' => 'HIT_Racks',
		'lhs_table' => 'hit_racks',
		'lhs_key'   => 'hat_assets_id',
		'rhs_module' => 'HAT_Assets',
		'rhs_table' => 'hat_assets',
		'rhs_key'   => 'id',
		'relationship_type' => 'one-to-one',
		),
	'hit_rack_allocations_hit_racks' => 
	array (
		'lhs_module' => 'HIT_Racks',
		'lhs_table' => 'hit_racks',
		'lhs_key'   => 'id',
		'rhs_module' => 'HIT_Rack_Allocations',
		'rhs_table' => 'hit_rack_allocations',
		'rhs_key'   => 'hit_racks_id',
		'relationship_type' => 'one-to-many',
		),
	),
'optimistic_locking'=>true,
'unified_search'=>true,
);
if (!class_exists('VardefManager')){
	require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('HIT_Racks','HIT_Racks', array('basic','assignable','security_groups'));