<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/

$dictionary['HAT_Assets'] = array(
  'table'=>
  'hat_assets',
  'audited'=>true,
  'inline_edit'=>true,
  'duplicate_merge'=>true,
  'fields'=>array (
    'name' =>
    array (
      'name' => 'name',
      'vname' => 'LBL_NAME',
      'type' => 'name',
      'link' => true,
      'dbType' => 'varchar',
      'len' => '255',
      'unified_search' => false,
      'full_text_search' =>
      array (
        'boost' => 3,
        ),
      'required' => true,
      'importable' => 'required',
      'duplicate_merge' => 'disabled',
      'merge_filter' => 'disabled',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'size' => '20',
      ),
    'asset_desc' =>
    array (
      'required' => true,
      'name' => 'asset_desc',
      'vname' => 'LBL_ASSET_DESC',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'asset_status' =>
    array (
      'required' => false,
      'name' => 'asset_status',
      'vname' => 'LBL_ASSET_STATUS',
      'type' => 'enum',
      'massupdate' => '1',
      'default' => 'InService',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'asset_status_list',
      'studio' => 'visible',
      'dependency' => false,
      ),

    'asset_criticality' =>
    array (
      'required' => false,
      'name' => 'asset_criticality',
      'vname' => 'LBL_ASSET_CRITICALITY',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'asset_criticality_list',
      'studio' => 'visible',
      'dependency' => false,
      ),
    'serial_number' =>
    array (
      'required' => false,
      'name' => 'serial_number',
      'vname' => 'LBL_SERIAL_NUMBER',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'tracking_number' =>
    array (
      'required' => false,
      'name' => 'tracking_number',
      'vname' => 'LBL_TRACKING_NUMBER',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'asset_name' =>
    array (
      'required' => true,
      'name' => 'asset_name',
      'vname' => 'LBL_ASSET_DESC',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'brand' =>
    array (
      'required' => false,
      'name' => 'brand',
      'vname' => 'LBL_BRAND',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'model' =>
    array (
      'required' => false,
      'name' => 'model',
      'vname' => 'LBL_MODEL',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'engine_num' =>
    array (
      'required' => false,
      'name' => 'engine_num',
      'vname' => 'LBL_ENGINE_NUM',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'vin' =>
    array (
      'required' => false,
      'name' => 'vin',
      'vname' => 'LBL_VIN',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'asset_number' =>
    array (
      'required' => false,
      'name' => 'asset_number',
      'vname' => 'LBL_ASSET_NUMBER',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'weight' =>
    array (
      'required' => false,
      'name' => 'weight',
      'vname' => 'LBL_WEIGHT',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'size' =>
    array (
      'required' => false,
      'name' => 'size',
      'vname' => 'LBL_SIZE',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'attribute1' =>
    array (
      'required' => false,
      'name' => 'attribute1',
      'vname' => 'LBL_ATTRIBUTE1',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'attribute2' =>
    array (
      'required' => false,
      'name' => 'attribute2',
      'vname' => 'LBL_ATTRIBUTE2',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'attribute3' =>
    array (
      'required' => false,
      'name' => 'attribute3',
      'vname' => 'LBL_ATTRIBUTE3',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'attribute4' =>
    array (
      'required' => false,
      'name' => 'attribute4',
      'vname' => 'LBL_ATTRIBUTE4',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'attribute5' =>
    array (
      'required' => false,
      'name' => 'attribute5',
      'vname' => 'LBL_ATTRIBUTE5',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'attribute6' =>
    array (
      'required' => false,
      'name' => 'attribute6',
      'vname' => 'LBL_ATTRIBUTE6',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'attribute7' =>
    array (
      'required' => false,
      'name' => 'attribute7',
      'vname' => 'LBL_ATTRIBUTE7',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'attribute8' =>
    array (
      'required' => false,
      'name' => 'attribute8',
      'vname' => 'LBL_ATTRIBUTE8',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'attribute9' =>
    array (
      'required' => false,
      'name' => 'attribute9',
      'vname' => 'LBL_ATTRIBUTE9',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'attribute10' =>
    array (
      'required' => false,
      'name' => 'attribute10',
      'vname' => 'LBL_ATTRIBUTE10',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),

    'location_desc' =>
    array (
      'required' => false,
      'name' => 'location_desc',
      'vname' => 'LBL_LOCATION_DESC',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'asset_source_type' =>
    array (
      'required' => true,
      'name' => 'asset_source_type',
      'vname' => 'LBL_SOURCE_TYPE',
      'type' => 'enum',
      'massupdate' => '1',
      'default' => 'PURCHASE',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'hat_asset_source_type_list',
      'studio' => 'visible',
      'dependency' => false,
      ),
    'asset_source_ref' =>
    array (
      'required' => false,
      'name' => 'asset_source_ref',
      'vname' => 'LBL_SOURCE_REF',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'asset_source_details' =>
    array (
      'required' => false,
      'name' => 'asset_source_details',
      'vname' => 'LBL_SOURCE_DETAILS',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'currency_id' =>
    array(
      'required' => false,
      'name' => 'currency_id',
      'vname' => 'LBL_CURRENCY',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 36,
      'studio' => 'visible',
      'function' =>
      array(
        'name' => 'getCurrencyDropDown',
        'returns' => 'html',
        ),
      ),
    'original_cost' =>
    array(
      'required' => false,
      'name' => 'original_cost',
      'vname' => 'LBL_PRIGINAL_COST',
      'type' => 'currency',
      'len' => '26,6',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => true,
      'enable_range_search' => true,
      'options' => 'numeric_range_search_dom',
      ),
    'linear_start_measure' =>
    array(
      'required' => false,
      'name' => 'linear_start_measure',
      'vname' => 'LBL_LINEAR_START',
      'type' => 'currency',
      'len' => '26,6',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => true,
      'enable_range_search' => true,
      'options' => 'numeric_range_search_dom',
      ),
    'linear_end_measure' =>
    array(
      'required' => false,
      'name' => 'linear_end_measure',
      'vname' => 'LBL_LINEAR_END',
      'type' => 'currency',
      'len' => '26,6',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => true,
      'enable_range_search' => true,
      'options' => 'numeric_range_search_dom',
      ),
    'linear_start_desc' =>
    array(
      'required' => false,
      'name' => 'linear_start_desc',
      'vname' => 'LBL_LINEAR_START_DESC',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => true,
      //'enable_range_search' => true,
      //'options' => 'numeric_range_search_dom',
      ),
    'linear_end_desc' =>
    array(
      'required' => false,
      'name' => 'linear_end_desc',
      'vname' => 'LBL_LINEAR_END_DESC',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => true,
      //'enable_range_search' => true,
      //'options' => 'numeric_range_search_dom',
      ),
    'linear_reference_method_id' =>
    array (
      'required' => false,
      'name' => 'linear_reference_method_id',
      'vname' => 'LBL_LINEAR_REFERENCE_METHOD_ID',
      'type' => 'id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
      ),
    'linear_reference_method' =>
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'linear_reference_method',
      'vname' => 'LBL_LINEAR_REFERENCE_METHOD_ID',
      'type' => 'relate',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'linear_reference_method_id',
      'ext2' => 'HAT_Linear_Reference_Methods',
      'module' => 'HAT_Linear_Reference_Methods',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      ),
    'warranty_expire_date' =>
    array (
      'required' => false,
      'name' => 'warranty_expire_date',
      'vname' => 'LBL_WARRANTY_EXPIRE',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      ),
    'received_date' =>
    array (
      'required' => false,
      'name' => 'received_date',
      'vname' => 'LBL_RECEIVED_DATE',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      ),
    'dismiss_date' =>
    array (
      'required' => false,
      'name' => 'dismiss_date',
      'vname' => 'LBL_DISMISS_DATE',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      ),
    'start_date' =>
    array (
      'required' => false,
      'name' => 'start_date',
      'vname' => 'LBL_START_DATE',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      ),
    'maintainable' =>
    array (
      'required' => false,
      'name' => 'maintainable',
      'vname' => 'LBL_MAINTAINABLE',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '1',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      ),
    'enable_vehicle_mgmt' =>
    array (
      'required' => false,
      'name' => 'enable_vehicle_mgmt',
      'vname' => 'LBL_ENABLE_VEHICLE_MGMT',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      ),
    'enable_it_ports' =>
    array (
      'required' => false,
      'name' => 'enable_it_ports',
      'vname' => 'LBL_ENABLE_IT_PORTS',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      ),
    'enable_it_rack' =>
    array (
      'required' => false,
      'name' => 'enable_it_rack',
      'vname' => 'LBL_ENABLE_IT_RACK',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      ),
    'enable_linear' =>
    array (
      'required' => false,
      'name' => 'enable_linear',
      'vname' => 'LBL_ENABLE_LINEAR',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      ),
    'enable_fa' =>
    array (
      'required' => false,
      'name' => 'enable_fa',
      'vname' => 'LBL_ENABLE_FA',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '1',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      ),    
    'use_location_gis' =>
    array (
      'required' => false,
      'name' => 'use_location_gis',
      'vname' => 'LBL_USE_LOCATION_GIS',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '1',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      ),
    'invalid_date' =>
    array (
      'required' => false,
      'name' => 'invalid_date',
      'vname' => 'LBL_INVALID_DATE',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'aos_products_id' =>
    array (
      'inline_edit' => 1,
      'required' => false,
      //'source' => 'custom_fields',
      'name' => 'aos_products_id',
      'vname' => 'LBL_ASSET_GROUP_AOS_PRODUCTS_ID',
      'type' => 'id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'HAT_Assetsaos_products_id',
      //'custom_module' => 'HAT_Assets',
      ),
    'asset_group' =>
    array (
      'inline_edit' => '1',
      'labelValue' => 'Product/Asset Group',
      'required' => true,
      'source' => 'non-db',
      'name' => 'asset_group',
      'vname' => 'LBL_ASSET_GROUP',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'aos_products_id',
      'ext2' => 'AOS_Products',
      'module' => 'AOS_Products',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      'id' => 'HAT_Assetsaos_products_id',
      //'custom_module' => 'HAT_Assets',
      ),
    'asset_name_rule' =>
    array (
      'inline_edit' => '1',
      'labelValue' => 'Product/Asset Group',
      'required' => true,
      'name' => 'asset_name_rule',
      'vname' => 'LBL_ASSET_NAME_RULE',
      'type' => 'enum',
      'options' => 'hat_asset_name_rule_list',
      'id_name' => 'aos_products_id',
      'ext2' => 'AOS_Products',
      'module' => 'AOS_Products',
      'rname' => 'asset_name_rule_c',
      'studio' => 'visible',
      //'custom_module' => 'HAT_Assets',
      ),
    'aos_product_categories_id' =>
    array (
      'inline_edit' => 1,
      'required' => false,
      //'source' => 'custom_fields',
      'name' => 'aos_product_categories_id',
      'vname' => 'LBL_ASSET_CATEGORY_AOS_PRODUCT_CATEGORIES_ID',
      'type' => 'id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'HAT_Assetsaos_product_categories_id',
      //'custom_module' => 'HAT_Assets',
      ),
    'asset_category' =>
    array (
      'inline_edit' => '1',
      'labelValue' => 'Asset Category',
      'required' => true,
      'source' => 'non-db',
      'name' => 'asset_category',
      'vname' => 'LBL_ASSET_CATEGORY',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'aos_product_categories_id',
      'ext2' => 'AOS_Product_Categories',
      'module' => 'AOS_Product_Categories',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      'id' => 'HAT_Assetsasset_category',
      //'custom_module' => 'HAT_Assets',
      ),
    'warranty_type_id' =>
    array (
      'required' => false,
      'name' => 'warranty_type_id',
      'vname' => 'LBL_WARRANTY_TYPE_ID',
      'type' => 'id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
      ),
    'warranty_type' =>
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'warranty_type',
      'vname' => 'LBL_WARRANTY_TYPE',
      'type' => 'relate',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'warranty_type_id',
      'ext2' => 'HAT_Warranty_Types',
      'module' => 'HAT_Warranty_Types',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      ),
    'parent_asset_id' =>
    array (
      'inline_edit' => 1,
      'required' => false,
     // 'source' => 'custom_fields',
      'name' => 'parent_asset_id',
      'vname' => 'LBL_PARENT_ASSET_ID',
      'type' => 'id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'HAT_Assetsparent_asset_id',
      //'custom_module' => 'HAT_Assets',
      ),
    'parent_asset' =>
    array (
      'inline_edit' => false,
      'labelValue' => 'Parent Asset',
      'required' => false,
      'source' => 'non-db',
      'name' => 'parent_asset',
      'vname' => 'LBL_PARENT_ASSET',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'parent_asset_id',
      'ext2' => 'HAT_Assets',
      'module' => 'HAT_Assets',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      'id' => 'HAT_Assetsparent_asset',
      //'custom_module' => 'HAT_Assets',
      ),
    'supplier_org_id' =>
    array (
      'inline_edit' => 1,
      'required' => false,
     // 'source' => 'custom_fields',
      'name' => 'supplier_org_id',
      'vname' => 'LBL_SUPPLIER_ORG_ID',
      'type' => 'id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'HAT_Assetssupplier_id',
      //'custom_module' => 'HAT_Assets',
      ),
    'supplier_org' =>
    array (
      'inline_edit' => '1',
      'labelValue' => 'Supplier/Provider',
      'required' => false,
      'source' => 'non-db',
      'name' => 'supplier_org',
      'vname' => 'LBL_SUPPLIER_ORG',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'supplier_org_id',
      'ext2' => 'Accounts',
      'module' => 'Accounts',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      'id' => 'HAT_Assetssupplier',
      //'custom_module' => 'HAT_Assets',
      ),
    'asset_status_taged' =>
    array (
        'source' => 'non-db', //从EventType映射
        'name' => 'asset_status_taged',
        'vname' => 'LBL_ASSET_STATUS',
        'type' => 'varchar',
        'default'=>'',
        'reportable' => true,
        'studio' => 'visible'
        ),

    'linear_length' =>
    array (
      'source' => 'non-db',
      'name' => 'linear_length',
      'vname' => 'LBL_LINEAR_LENGTH',
      'type' => 'varchar',
      'reportable' => true,
      'studio' => 'visible'
      ),

    'map_type' =>
    array (
            'source' => 'non-db', //Location
            'name' => 'map_type',
            'default'=>'NONE',
            'vname' => 'LBL_MAP_TYPE',
            'type' => 'enum',
            'reportable' => true,
            'studio' => 'visible',
            'options' => 'cux_map_type_list',
            ),
    'asset_map_type' =>
    array (
      'required' => true,
      'default' => "NONE",
      'name' => 'asset_map_type',
      'vname' => 'ASSET_LBL_MAP_TYPE',
      'type' => 'enum',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'options' => 'cux_map_type_list',
      ),

    'map_lat' =>
    array (
            'source' => 'non-db', //Location
            'name' => 'map_lat',
            'vname' => 'LBL_MAPS_LAT_C',
            'type' => 'relate',
            'reportable' => true,
            'studio' => 'visible',
            'precision' => '8',
            ),
    'asset_map_lat' =>
    array (
      'required' => true,
      'name' => 'asset_map_lat',
      'vname' => 'ASSET_LBL_MAP_LAT_C',
      'type' => 'float',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'default' => '0.00000000',
      'len' => '11',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '8',
      ),

    'map_lng' =>
    array (
            'source' => 'non-db', //Location
            'name' => 'map_lng',
            'vname' => 'LBL_MAPS_LNG_C',
            'type' => 'relate',
            'reportable' => true,
            'studio' => 'visible',
            'precision' => '8',
            ),
    'asset_map_lng' =>
    array (
      'required' => true,
      'name' => 'asset_map_lng',
      'vname' => 'ASSET_LBL_MAP_LNG_C',
      'type' => 'float',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'default' => '0.00000000',
      'len' => '11',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '8',
      ),

    'map_zoom' =>
    array (
            'source' => 'non-db', //Location
            'name' => 'map_zoom',
            'vname' => 'LBL_MAPS_ZOOM',
            'type' => 'int',
            'reportable' => true,
            'studio' => 'visible',
            ),
    'asset_map_zoom' =>
    array (
      'required' => true,
      'name' => 'asset_map_zoom',
      'vname' => 'ASSET_LBL_MAP_ZOOM',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'default' => '13',
      ),
    'map_marker_type' =>
    array (
              'source' => 'non-db', //Location
              'name' => 'map_marker_type',
              'vname' => 'LBL_MAP_MARKER_TYPE',
              'type' => 'enum',
              'reportable' => true,
              'studio' => 'visible',
              'options' => 'hat_map_marker_type_list',
              ),
    'asset_map_marker_type' =>
    array (
      'required' => true,
      'default' => "NONE",
      'name' => 'asset_map_marker_type',
      'vname' => 'ASSET_LBL_MAP_MARKER_TYPE',
      'type' => 'enum',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'options' => 'hat_map_marker_type_list',
      ),
    'map_marker_data' =>
    array (
              'source' => 'non-db', //Location
              'name' => 'map_marker_data',
              'vname' => 'LBL_MAPS_ZOOM',
              'type' => 'relate',
              'reportable' => true,
              'studio' => 'visible',
              ),
    'asset_map_marker_data' =>
    array (
      'required' => false,
      'name' => 'asset_map_marker_data',
      'vname' => 'ASSET_LBL_MAP_MARKER_DATA',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'map_search_area' =>
    array (
      'name' => 'map_search_area',
      'vname' => 'LBL_MAP_SEARCH_AREA',
      'source' => 'non-db',
      'type' => 'varchar',
      'massupdate' => 0,
      ),
    'map_display_area' =>
    array (
            'source' => 'non-db', //Location
            'name' => 'map_display_area',
            'vname' => 'LBL_MAP_DISPLAY_AREA',
            'type' => 'varchar',
            'reportable' => true,
            'studio' => 'visible'
            ),
    'map_layer_id' =>
    array (
          'source' => 'non-db', //Location
          'name' => 'map_layer_id',
          'vname' => 'LBL_MAP_LAYER_ID',
          'type' => 'relate',
          'reportable' => true,
          'studio' => 'visible',
          ),
    'asset_map_layer_id' =>
    array (
      'required' => false,
      'name' => 'asset_map_layer_id',
      'vname' => 'ASSET_LBL_MAP_LAYER_ID',
      'type' => 'id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => false,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
      ),
    'map_layer' =>
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'map_layer',
      'vname' => 'LBL_MAP_LAYER',
      'type' => 'relate',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => false,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'asset_map_layer_id',
      'ext2' => 'HAA_Maps',
      'module' => 'HAA_Maps',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      ),
    'map_layer_url' =>
    array (
      'name' => 'map_layer_url',
      'id_name' => 'map_layer_id',
      'type' => 'relate',
              'rname' => 'map_file',//which points to the field name in the related module record
              'vname' => 'LBL_MAP_LAYER_URL',
              'link' => 'map_layer',//'map_layer_link',
              'module' => 'HAA_Maps',
              'source' => 'non-db', //HAA_Maps
              'dbType' => 'non-db', //HAA_Maps
              'studio' => 'visible',
              ),
     //location -non-db end
    'treeview_display_area' =>
    array (
            'source' => 'non-db', //Location
            'name' => 'treeview_display_area',
            'vname' => 'LBL_TREEVIEW_DISPLAY_AREA',
            'type' => 'varchar',
            'reportable' => true,
            'studio' => 'visible'
            ),
    'hit_racks_id' =>
    array (
            'source' => 'non-db', //Location
            'name' => 'hit_racks_id',
            'vname' => 'LBL_RACKS',
            'type' => 'varchar',
            'reportable' => true,
            'studio' => 'visible'
            ),
    'hit_racks' =>
    array (
            'source' => 'non-db', //Location
            'name' => 'hit_racks',
            'vname' => 'LBL_HIT_RACKS',
            'type' => 'varchar',
            'reportable' => true,
            'studio' => 'visible',
            ),
    'using_details' =>
    array (
      'required' => false,
      'name' => 'using_details',
      'vname' => 'LBL_USING_DETAILS',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'owning_details' =>
    array (
      'required' => false,
      'name' => 'owning_details',
      'vname' => 'LBL_OWNING_DETAILS',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'using_person_id' =>
    array (
      'required' => false,
      'name' => 'using_person_id',
      'vname' => 'LBL_USING_PERSON_ID',
      'type' => 'id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
      ),
    'supplier_desc' =>
    array (
      'required' => false,
      'name' => 'supplier_desc',
      'vname' => 'LBL_USING_PERSON_DESC',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'using_person_desc' =>
    array (
      'required' => false,
      'name' => 'using_person_desc',
      'vname' => 'LBL_USING_PERSON_DESC',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),
    'owning_person_desc' =>
    array (
      'required' => false,
      'name' => 'owning_person_desc',
      'vname' => 'LBL_OWNING_PERSON_DESC',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      ),    
    'using_person' =>
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'using_person',
      'vname' => 'LBL_USING_PERSON',
      'type' => 'relate',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'using_person_id',
      'ext2' => 'Contacts',
      'module' => 'Contacts',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      ),
    'owning_person_id' =>
    array (
      'required' => false,
      'name' => 'owning_person_id',
      'vname' => 'LBL_OWNING_PERSON_ID',
      'type' => 'id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
      ),
    'owning_person' =>
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'owning_person',
      'vname' => 'LBL_OWNING_PERSON',
      'type' => 'relate',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'owning_person_id',
      'ext2' => 'Contacts',
      'module' => 'Contacts',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      ),
    'using_org_id' =>
    array (
      'required' => false,
      'name' => 'using_org_id',
      'vname' => 'LBL_USING_ORG_ID',
      'type' => 'id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
      ),
    'using_org' =>
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'using_org',
      'vname' => 'LBL_USING_ORG',
      'type' => 'relate',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'using_org_id',
      'ext2' => 'Accounts',
      'module' => 'Accounts',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      ),
    'owning_org_id' =>
    array (
      'required' => false,
      'name' => 'owning_org_id',
      'vname' => 'LBL_OWING_ORG_ID',
      'type' => 'id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
      ),
    'owning_org' =>
    array (
      'required' => true,
      'source' => 'non-db',
      'name' => 'owning_org',
      'vname' => 'LBL_OWING_ORG',
      'type' => 'relate',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'owning_org_id',
      'ext2' => 'Accounts',
      'module' => 'Accounts',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      ),
    'asset_source_id' =>
    array (
      'required' => false,
      'name' => 'asset_source_id',
      'vname' => 'LBL_ASSET_SOURCE_ID',
      'type' => 'id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
      ),
    'asset_source' =>
    array (
      'required' => true,
      'source' => 'non-db',
      'name' => 'asset_source',
      'vname' => 'LBL_ASSET_SOURCE',
      'type' => 'relate',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'asset_source_id',
      'ext2' => 'HAT_Asset_Sources',
      'module' => 'HAT_Asset_Sources',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      ),
    'haa_frameworks_id' =>
    array (
      'required' => false,
      'name' => 'haa_frameworks_id',
      'vname' => 'LBL_FRAMEWORK_ID',
      'type' => 'id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
      ),
    'framework' =>
    array (
      'required' => true,
      'source' => 'non-db',
      'name' => 'framework',
      'vname' => 'LBL_FRAMEWORK',
      'type' => 'relate',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'haa_frameworks_id',
      'ext2' => 'HAA_Frameworks',
      'module' => 'HAA_Frameworks',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      ),
    'asset_icon' =>
    array (
      'required' => false,
      'name' => 'asset_icon',
      'vname' => 'LBL_ICON',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      ),
    'fixed_asset_id'=> array (
      'required' => false,
      'name' => 'fixed_asset_id',
      'vname' => 'LBL_FIXED_ASSET_ID',
      'type' => 'id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',

    ),
    'fixed_asset' => array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'fixed_asset',
      'vname' => 'LBL_FIXED_ASSET',
      'type' => 'relate',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'fixed_asset_id',
      'ext2' => 'HFA_Fixed_Assets',
      'module' => 'HFA_Fixed_Assets',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'ham_sr_link' =>
    array(
      'name' => 'ham_sr_link',
      'type' => 'link',
      'relationship' => 'ham_sr_hat_assets',
      'link_type' => 'many',
      'module' => 'HAM_SR',
      'bean_name' => 'HAM_SR',
      'source' => 'non-db',
      ),

    'ham_wo_link' =>
    array(
      'name' => 'ham_wo_link',
      'type' => 'link',
      'relationship' => 'ham_wo_hat_assets',
      'link_type' => 'many',
      'module' => 'HAM_WO',
      'bean_name' => 'HAM_WO',
      'source' => 'non-db',
      ),
    'hat_linear_elements_link' =>
    array(
      'name' => 'hat_linear_elements_link',
      'type' => 'link',
      'relationship' => 'hat_linear_elements',
      'link_type' => 'many',
      'module' => 'HAT_Linear_Elements',
      'bean_name' => 'HAT_Linear_Elements',
      'source' => 'non-db',
      ),
    'hat_meters_hat_assets_link' =>
    array(
      'name' => 'hat_meters_hat_assets_link',
      'type' => 'link',
      'relationship' => 'hat_meters_hat_assets',
      'link_type' => 'many',
      'module' => 'HAT_Assets',
      'bean_name' => 'HAT_Assets',
      'source' => 'non-db',
      ),
    ),
'relationships'=>array (
  'ham_sr_hat_assets' =>
  array (
    'lhs_module' => 'HAT_Assets',
    'lhs_table' => 'hat_assets',
    'lhs_key' => 'id',
    'rhs_module' => 'HAM_SR',
    'rhs_table' => 'ham_sr',
    'rhs_key' => 'hat_assets_id',
    'relationship_type' => 'one-to-many',
    ),
  'ham_wo_hat_assets' =>
  array (
    'lhs_module' => 'HAT_Assets',
    'lhs_table' => 'hat_assets',
    'lhs_key' => 'id',
    'rhs_module' => 'HAM_WO',
    'rhs_table' => 'ham_wo',
    'rhs_key' => 'hat_assets_id',
    'relationship_type' => 'one-to-many',
    ),
  'hat_linear_elements' =>
  array (
    'lhs_module' => 'HAT_Assets',
    'lhs_table' => 'hat_assets',
    'lhs_key' => 'id',
    'rhs_module' => 'HAT_Linear_Elements',
    'rhs_table' => 'hat_linear_elements',
    'rhs_key' => 'parent_asset_id',
    'relationship_type' => 'one-to-many',
    ),
  'hat_meters_hat_assets' =>
  array (
    'lhs_module' => 'HAT_Assets',
    'lhs_table' => 'hat_assets',
    'lhs_key' => 'id',
    'rhs_module' => 'HAT_Meters',
    'rhs_table' => 'hat_meters',
    'rhs_key' => 'hat_assets_id',
    'relationship_type' => 'one-to-many',
    ),


  ),
'optimistic_locking'=>true,
'unified_search'=>true,
);
if (!class_exists('VardefManager')){
  require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('HAT_Assets','HAT_Assets', array('basic','assignable','security_groups'));