<?php

$dictionary['HMM_Trans_Lines'] = array(
	'table'=>'hmm_trans_lines',
	'audited'=>true,
	'inline_edit'=>false,
	'duplicate_merge'=>false,
	'fields'=>array (
		'trans_batch_id' => 
		array (
			'required' => false,
			'name' => 'trans_batch_id',
			'vname' => 'LBL_TRANS_BATCH_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'ham_maint_sites_id' => 
		array (
			'required' => false,
			'name' => 'ham_maint_sites_id',
			'vname' => 'LBL_SITE_HAM_MAINT_SITES_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'site' => 
		array (
			'required' => true,
			'source' => 'non-db',
			'name' => 'site',
			'vname' => 'LBL_SITE',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => '',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'ham_maint_sites_id',
			'ext2' => 'HAM_Maint_Sites',
			'module' => 'HAM_Maint_Sites',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'hat_event_type_id' => 
		array (
			'required' => false,
			'name' => 'hat_event_type_id',
			'vname' => 'LBL_EVENT_TYPE_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => false,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'event_type' =>
		array (
			'required' => true,
			'source' => 'non-db',
			'name' => 'event_type',
			'vname' => 'LBL_EVENT_TYPE',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'hat_event_type_id',
			'ext2' => 'HAT_EventType',
			'module' => 'HAT_EventType',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'trans_basic_type_lov' =>
		array (
			'source' => 'non-db',
			'name' => 'trans_basic_type_lov',
			'vname' => 'LBL_TRANS_BASIC_TYPE',
			'type' => 'enum',
			'reportable' => true,
			'studio' => 'visible',
			'options' => 'cux_event_type_list',
			),
		'trans_basic_type' =>
		array (
			'source' => 'non-db',
			'name' => 'trans_basic_type',
			'vname' => 'LBL_TRANS_BASIC_TYPE',
			'type' => 'varchar',
			'reportable' => true,
			'studio' => 'visible',
			),
		'item_id' =>
		array (
			'required' => false,
			'name' => 'item_id',
			'vname' => 'LBL_ITEM_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'inventory_item' =>
		array (
			'required' => true,
			'source' => 'non-db',
			'name' => 'inventory_item',
			'vname' => 'LBL_ITEM',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'item_id',
			'ext2' => 'AOS_Products',
			'module' => 'AOS_Products',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'hmm_mo_requests_id' =>
		array (
			'required' => false,
			'name' => 'hmm_mo_requests_id',
			'vname' => 'LBL_HMM_MO_REQUESTS_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'hmm_mo_request' =>
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'hmm_mo_request',
			'vname' => 'LBL_HMM_MO_REQUESTS',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'hmm_mo_requests_id',
			'ext2' => 'HMM_MO_Requests',
			'module' => 'HMM_MO_Requests',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'ham_woop_id' =>
		array (
			'required' => false,
			'name' => 'ham_woop_id',
			'vname' => 'LBL_WOOP_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'ham_woop' =>
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'ham_woop',
			'vname' => 'LBL_WOOP',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'ham_woop_id',
			'ext2' => 'HAM_WOOP',
			'module' => 'HAM_WOOP',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'primary_qty' =>
		array(
			'required' => true,
			'name' => 'primary_qty',
			'vname' => 'LBL_PRIMARY_QTY',
			'type' => 'decimal',
			'len' => '18,6',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => 1,
			'reportable' => true,
			'enable_range_search' => true,
			'options' => 'numeric_range_search_dom',
			),
		'secondary_qty' =>
		array(
			'required' => '0',
			'name' => 'secondary_qty',
			'vname' => 'LBL_SECONDARY_QTY',
			'type' => 'currency',
			'len' => '18,6',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => 1,
			'reportable' => true,
			'enable_range_search' => true,
			'options' => 'numeric_range_search_dom',
			),
		'trans_date' =>
		array (
			'required' => true,
			'name' => 'trans_date',
			'vname' => 'LBL_TRANS_DATE',
			'type' => 'datetimecombo',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'size' => '20',
			'enable_range_search' => false,
			'dbType' => 'datetime',
			'display_default' => 'now',
			),
		'primary_uom_id' =>
		array (
			'required' => false,
			'name' => 'primary_uom_id',
			'vname' => 'LBL_PRIMARY_UOM_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'primary_uom' =>
		array (
			'required' => true,
			'source' => 'non-db',
			'name' => 'primary_uom',
			'vname' => 'LBL_PRIMARY_UOM',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'primary_uom_id',
			'ext2' => 'HAA_UOM',
			'module' => 'HAA_UOM',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'secondary_uom_id' =>
		array (
			'required' => false,
			'name' => 'secondary_uom_id',
			'vname' => 'LBL_SECONDARY_UOM_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'secondary_uom' =>
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'secondary_uom',
			'vname' => 'LBL_SECONDARY_UOM',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'secondary_uom_id',
			'ext2' => 'HAA_UOM',
			'module' => 'HAA_UOM',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'from_location_id' =>
		array (
			'required' => false,
			'name' => 'from_location_id',
			'vname' => 'LBL_FROM_LOCATION_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'from_location' =>
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'from_location',
			'vname' => 'LBL_FROM_LOCATION',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'from_location_id',
			'ext2' => 'HAT_Asset_Locations',
			'module' => 'HAT_Asset_Locations',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'to_location_id' =>
		array (
			'required' => false,
			'name' => 'to_location_id',
			'vname' => 'LBL_TO_LOCATION_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'to_location' =>
		array (
			'required' => true,
			'source' => 'non-db',
			'name' => 'to_location',
			'vname' => 'LBL_TO_LOCATION',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'to_location_id',
			'ext2' => 'HAT_Asset_Locations',
			'module' => 'HAT_Asset_Locations',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'from_locator_id' =>
		array (
			'required' => false,
			'name' => 'from_locator_id',
			'vname' => 'LBL_FROM_LOCATOR_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'from_locator' =>
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'from_locator',
			'vname' => 'LBL_FROM_LOCATOR',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'from_locator_id',
			'ext2' => 'HMM_Locators',
			'module' => 'HMM_Locators',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'to_locator_id' => 
		array (
			'required' => false,
			'name' => 'to_locator_id',
			'vname' => 'LBL_TO_LOCATOR_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'to_locator' =>
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'to_locator',
			'vname' => 'LBL_TO_LOCATOR',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'to_locator_id',
			'ext2' => 'HMM_Locators',
			'module' => 'HMM_Locators',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'from_locator_control' =>
		array (
			'source' => 'non-db',
			'name' => 'from_locator_control',
			'vname' => 'LBL_FROM_LOCATOR_CONTROL',
			'type' => 'varchar',
			'reportable' => true,
			'studio' => 'visible',
			),
		'secondary_unit_defaulting_lov' =>
		array (
			'source' => 'non-db',
			'name' => 'secondary_unit_defaulting_lov',
			'vname' => 'LBL_SECONDARY_UNIT_DEFAULTING',
			  'type' => 'enum',// 'enum',
			  'reportable' => true,
			  'studio' => 'visible',
			  'options' => 'cux_products_secondary_unit_defaulting_list',
			  ),
		'secondary_unit_defaulting' =>
		array (
			'source' => 'non-db',
			'name' => 'secondary_unit_defaulting',
			'vname' => 'LBL_SECONDARY_UNIT_DEFAULTING',
			  'type' => 'varchar',// 'enum',
			  'reportable' => true,
			  'studio' => 'visible',
			  ),
		'tracking_uom_lov' =>
		array (
			'source' => 'non-db',
			'name' => 'tracking_uom_lov',
			'vname' => 'LBL_TRACKING_UOM',
			  'type' => 'enum',// 'enum',
			  'reportable' => true,
			  'studio' => 'visible',
			  'options' => 'cux_products_uom_usage_list',
			  ),
		'tracking_uom' =>
		array (
			'source' => 'non-db',
			'name' => 'tracking_uom',
			'vname' => 'LBL_TRACKING_UOM',
			'type' => 'varchar',
			'reportable' => true,
			'studio' => 'visible',
			),
		'locator_control_lov' => 
		array (
			'source' => 'non-db',
			'name' => 'locator_control_lov',
			'vname' => 'LBL_LOCATOR_CONTROL',
			  'type' => 'enum',// 'enum',
			  'reportable' => true,
			  'studio' => 'visible',
			  'options' => 'hat_inventory_node_list',
			  ),
		'to_locator_control' => 
		array (
			'source' => 'non-db',
			'name' => 'to_locator_control',
			'vname' => 'LBL_TO_LOCATOR_CONTROL',
			  'type' => 'varchar',// 'enum',
			  'reportable' => true,
			  'studio' => 'visible',
			  ),
		'uom_conversion' => 
		array (
			'source' => 'non-db',
			'name' => 'uom_conversion',
			'vname' => 'LBL_UOM_CONVERSION',
			  'type' => 'varchar',// 'enum',
			  'reportable' => true,
			  'studio' => 'visible',
			  ),
		),
'relationships'=>array (
	),
'optimistic_locking'=>true,
'unified_search'=>true,
);
if (!class_exists('VardefManager')){
	require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('HMM_Trans_Lines','HMM_Trans_Lines', array('basic','assignable','security_groups'));