<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/

$dictionary['HAM_ACT'] = array(
	'table'=>'ham_act',
	'audited'=>true,
    'inline_edit'=>true,
		'duplicate_merge'=>true,
		'fields'=>array (
    'haa_frameworks_id' =>
    array (
      'required' => false,
      'name' => 'haa_frameworks_id',
      'vname' => 'LBL_FRAMEWORK_ID',
      'type' => 'id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
      ),
    'framework' =>
    array (
      'required' => true,
      'source' => 'non-db',
      'name' => 'framework',
      'vname' => 'LBL_FRAMEWORK',
      'type' => 'relate',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'haa_frameworks_id',
      'ext2' => 'HAA_Frameworks',
      'module' => 'HAA_Frameworks',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      ),
'act_status' => 
      array (
            'required' => true,
            'name' => 'act_status',
            'vname' => 'LBL_ACT_STATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'ham_wo_status_list',
            'studio' => 'visible',
            'dependency' => false,
            ),
			
'hat_event_type_id' => 
      array (
            'required' => false,
            'name' => 'hat_event_type_id',
            'vname' => 'LBL_EVENT_TYPE_ID',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'size' => '20',
            ),
'event_type' => 
      array (
            'required' => false,
            'source' => 'non-db',
            'name' => 'event_type',
            'vname' => 'LBL_EVENT_TYPE',
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'hat_event_type_id',
            'ext2' => 'HAT_EventType',
            'module' => 'HAT_EventType',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            ),
			
'sr_hat_domains_rule_id' => 
    array (
      'required' => false,
      'name' => 'sr_hat_domains_rule_id',
      'vname' => 'LBL_SR_HAA_FRAMEWORKS_RULE_ID',
      'type' => 'id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
      ),
'sr_hat_domains_rule' => 
    array (
      'required' => true,
      'source' => 'non-db',
      'name' => 'sr_hat_domains_rule',
      'vname' => 'LBL_SR_HAA_FRAMEWORKS_RULE',
      'type' => 'relate',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'sr_hat_domains_rule_id',
      'ext2' => 'HAA_Frameworks',
      'module' => 'HAA_Frameworks',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      	  ),

'sr_haa_codes_rule_id' => 
    array (
      'required' => false,
      'name' => 'sr_haa_codes_rule_id',
      'vname' => 'SR_HAA_CODES_RULE_ID',
      'type' => 'id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
      ),
'sr_haa_codes_rule' => 
    array (
      'required' => true,
      'source' => 'non-db',
      'name' => 'sr_haa_codes_rule',
      'vname' => 'SR_HAA_CODES_RULE',
      'type' => 'relate',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'sr_haa_codes_rule_id',
      'ext2' => 'HAA_Codes',
      'module' => 'HAA_Codes',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      ),	  
	  
'ham_priority_id' => 
      array (
            'required' => false,
            'name' => 'ham_priority_id',
            'vname' => 'LBL_PRIORITY_HAM_PRIORITY_ID',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'size' => '20',
            ),
'priority' => 
      array (
            'required' => true,
            'source' => 'non-db',
            'name' => 'priority',
            'vname' => 'LBL_PRIORITY',
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'ham_priority_id',
            'ext2' => 'HAM_Priority',
            'module' => 'HAM_Priority',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            ),
            'hat_asset_locations_id' => array (
                  'required' => false,
                  'name' => 'hat_asset_locations_id',
                  'vname' => 'LBL_LOCATION_HAT_ASSET_LOCATIONS_ID',
                  'type' => 'id',
                  'massupdate' => 0,
                  'no_default' => false,
                  'comments' => '',
                  'help' => '',
                  'importable' => 'true',
                  'duplicate_merge' => 'disabled',
                  'duplicate_merge_dom_value' => 0,
                  'audited' => false,
                  'inline_edit' => true,
                  'reportable' => false,
                  'unified_search' => false,
                  'merge_filter' => 'disabled',
                  'len' => 36,
                  'size' => '20',
                  ),
            'location' => array (
                  'required' => false,
                  'source' => 'non-db',
                  'name' => 'location',
                  'vname' => 'LBL_LOCATION',
                  'type' => 'relate',
                  'massupdate' => 0,
                  'no_default' => false,
                  'comments' => '',
                  'help' => '',
                  'importable' => 'true',
                  'duplicate_merge' => 'disabled',
                  'duplicate_merge_dom_value' => '0',
                  'audited' => false,
                  'inline_edit' => true,
                  'reportable' => true,
                  'unified_search' => false,
                  'merge_filter' => 'disabled',
                  'len' => '255',
                  'size' => '20',
                  'id_name' => 'hat_asset_locations_id',
                  'ext2' => 'HAT_Asset_Locations',
                  'module' => 'HAT_Asset_Locations',
                  'rname' => 'name',
                  'quicksearch' => 'enabled',
                  'studio' => 'visible',

                  
                  ),

            'ham_asset_routes_id' => array (
                  'required' => false,
                  'name' => 'ham_asset_routes_id',
                  'vname' => 'LBL_HAT_ASSET_ROUTES_ID',
                  'type' => 'id',
                  'massupdate' => 0,
                  'no_default' => false,
                  'comments' => '',
                  'help' => '',
                  'importable' => 'true',
                  'duplicate_merge' => 'disabled',
                  'duplicate_merge_dom_value' => 0,
                  'audited' => false,
                  'inline_edit' => true,
                  'reportable' => false,
                  'unified_search' => false,
                  'merge_filter' => 'disabled',
                  'len' => 36,
                  'size' => '20',
                  ),
            'ham_asset_routes' => array (
                  'required' => false,
                  'source' => 'non-db',
                  'name' => 'ham_asset_routes',
                  'vname' => 'LBL_ASSET',
                  'type' => 'relate',
                  'massupdate' => 0,
                  'no_default' => false,
                  'comments' => '',
                  'help' => '',
                  'importable' => 'true',
                  'duplicate_merge' => 'disabled',
                  'duplicate_merge_dom_value' => '0',
                  'audited' => false,
                  'inline_edit' => true,
                  'reportable' => true,
                  'unified_search' => false,
                  'merge_filter' => 'disabled',
                  'len' => '255',
                  'size' => '20',
                  'id_name' => 'ham_asset_routes_id',
                  'ext2' => 'HAT_Asset_Rules',
                  'module' => 'HAT_Asset_Rules',
                  'rname' => 'name',
                  'quicksearch' => 'enabled',
                  'studio' => 'visible',
                  ),

            'hat_assets_id' => array (
                  'required' => false,
                  'name' => 'hat_assets_id',
                  'vname' => 'LBL_HAT_ASSETS_ID',
                  'type' => 'id',
                  'massupdate' => 0,
                  'no_default' => false,
                  'comments' => '',
                  'help' => '',
                  'importable' => 'true',
                  'duplicate_merge' => 'disabled',
                  'duplicate_merge_dom_value' => 0,
                  'audited' => false,
                  'inline_edit' => true,
                  'reportable' => false,
                  'unified_search' => false,
                  'merge_filter' => 'disabled',
                  'len' => 36,
                  'size' => '20',
                  ),
            'asset' => array (
                  'required' => false,
                  'source' => 'non-db',
                  'name' => 'asset',
                  'vname' => 'LBL_ASSET',
                  'type' => 'relate',
                  'massupdate' => 0,
                  'no_default' => false,
                  'comments' => '',
                  'help' => '',
                  'importable' => 'true',
                  'duplicate_merge' => 'disabled',
                  'duplicate_merge_dom_value' => '0',
                  'audited' => false,
                  'inline_edit' => true,
                  'reportable' => true,
                  'unified_search' => false,
                  'merge_filter' => 'disabled',
                  'len' => '255',
                  'size' => '20',
                  'id_name' => 'hat_assets_id',
                  'ext2' => 'HAT_Assets',
                  'module' => 'HAT_Assets',
                  'rname' => 'name',
                  'quicksearch' => 'enabled',
                  'studio' => 'visible',
                  ),

'act_op_link' =>
      array(
        'name' => 'act_op_link',
        'type' => 'link',
        'relationship' => 'ham_act_op',
        'vname' => 'LBL_ACT_OP_SUBPANEL_TITLE',
        'link_type' => 'many',
        'module' => 'HAM_ACT_OP',
        'bean_name' => 'HAM_ACT_OP',
        'source' => 'non-db',
		),
		
),

'relationships'=>array (
	
'ham_act_op' =>
      array (
      'lhs_module' => 'HAM_ACT',
      'lhs_table' => 'ham_act',
      'lhs_key'   => 'id',
      'rhs_module' => 'HAM_ACT_OP',
      'rhs_table' => 'ham_act_op',
      'rhs_key'   => 'ham_act_id',
      'relationship_type' => 'one-to-many',
      ),
),
	'optimistic_locking'=>true,
		'unified_search'=>true,
	);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('HAM_ACT','HAM_ACT', array('basic','assignable','security_groups'));