<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/

$dictionary['HAA_Frameworks'] = array(
	'table'=>'haa_frameworks',
	'audited'=>true,
    'inline_edit'=>true,
    'duplicate_merge'=>true,
    'fields'=>array (
        'code' => 
        array (
          'required' => true,
          'name' => 'code',
          'vname' => 'LBL_CODE',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'inline_edit' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
          ),
        'default_product_uom_id' => 
        array (
            'required' => false,
            'name' => 'default_product_uom_id',
            'vname' => 'LBL_DEFAULT_PRODUCT_UOM_ID',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'size' => '20',
            ),
        'default_product_uom' => 
        array (
            'required' => false,
            'source' => 'non-db',
            'name' => 'default_product_uom',
            'vname' => 'LBL_DEFAULT_PRODUCT_UOM',
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'default_product_uom_id',
            'ext2' => 'HAA_UOM',
            'module' => 'HAA_UOM',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            ),
        'default_area_uom_class_id' => 
        array (
            'required' => false,
            'name' => 'default_area_uom_class_id',
            'vname' => 'LBL_DEFAULT_AREA_UOM_CLASS_ID',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'size' => '20',
            ),
        'hat_counting_policy_groups_id_c' => 
      array (
        'required' => false,
        'name' => 'hat_counting_policy_groups_id_c',
        'vname' => 'LBL_COUNTING_POLICY_GROUPS_HAT_COUNTING_POLICY_GROUPS_ID',
        'type' => 'id',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => 0,
        'audited' => false,
        'inline_edit' => true,
        'reportable' => false,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => 36,
        'size' => '20',
        ),
      'counting_policy_groups' => 
      array (
        'required' => false,
        'source' => 'non-db',
        'name' => 'counting_policy_groups',
        'vname' => 'LBL_COUNTING_POLICY_GROUPS',
        'type' => 'relate',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        'id_name' => 'hat_counting_policy_groups_id_c',
        'ext2' => 'HAT_Counting_Policy_Groups',
        'module' => 'HAT_Counting_Policy_Groups',
        'rname' => 'name',
        'quicksearch' => 'enabled',
        'studio' => 'visible',
        ),
       'hat_counting_task_templates_id_c' => 
        array (
            'required' => false,
            'name' => 'hat_counting_task_templates_id_c',
            'vname' => 'LBL_TASK_TEMPLATES_HAT_COUNTING_TASK_TEMPLATES_ID',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'size' => '20',
            ),
        'task_templates' => 
        array (
            'required' => false,
            'source' => 'non-db',
            'name' => 'task_templates',
            'vname' => 'LBL_TASK_TEMPLATES',
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'hat_counting_task_templates_id_c',
            'ext2' => 'HAT_Counting_Task_Templates',
            'module' => 'HAT_Counting_Task_Templates',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            ),
        'default_area_uom_class' => 
        array (
            'required' => false,
            'source' => 'non-db',
            'name' => 'default_area_uom_class',
            'vname' => 'LBL_DEFAULT_AREA_UOM_CLASS',
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'default_area_uom_class_id',
            'ext2' => 'HAA_UOM_Classes',
            'module' => 'HAA_UOM_Classes',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            ),
        'default_time_uom_class_id' => 
        array (
            'required' => false,
            'name' => 'default_time_uom_class_id',
            'vname' => 'LBL_DEFAULT_TIME_UOM_CLASS_ID',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'size' => '20',
            ),
        'default_time_uom_class' => 
        array (
            'required' => false,
            'source' => 'non-db',
            'name' => 'default_time_uom_class',
            'vname' => 'LBL_DEFAULT_TIME_UOM_CLASS',
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'default_time_uom_class_id',
            'ext2' => 'HAA_UOM_Classes',
            'module' => 'HAA_UOM_Classes',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            ),
        'haa_asset_numbering_rule_id' => 
        array (
            'required' => false,
            'name' => 'haa_asset_numbering_rule_id',
            'vname' => 'LBL_ASSET_NUMBERING_RULE_HAA_NUMBERING_RULE_ID',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'size' => '20',
            ),
        'asset_numbering_rule' => 
        array (
            'required' => false,
            'source' => 'non-db',
            'name' => 'asset_numbering_rule',
            'vname' => 'LBL_ASSET_NUMBERING_RULE',
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'haa_asset_numbering_rule_id',
            'ext2' => 'HAA_Numbering_Rule',
            'module' => 'HAA_Numbering_Rule',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            ),
        'haa_asset_counting_rule_id' => 
        array (
            'required' => false,
            'name' => 'haa_asset_counting_rule_id',
            'vname' => 'LBL_ASSET_COUNTING_RULE_ID',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'size' => '20',
            ),
        'asset_counting_rule' => 
        array (
            'required' => false,
            'source' => 'non-db',
            'name' => 'asset_counting_rule',
            'vname' => 'LBL_ASSET_COUNTING_RULE',
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'haa_asset_counting_rule_id',
            'ext2' => 'HAA_Numbering_Rule',
            'module' => 'HAA_Numbering_Rule',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            ),
        'haa_at_numbering_rule_id' => 
        array (
            'required' => false,
            'name' => 'haa_at_numbering_rule_id',
            'vname' => 'LBL_AT_NUMBERING_RULE_HAA_NUMBERING_RULE_ID',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'size' => '20',
            ),
        'at_numbering_rule' => 
        array (
            'required' => false,
            'source' => 'non-db',
            'name' => 'at_numbering_rule',
            'vname' => 'LBL_AT_NUMBERING_RULE',
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'haa_at_numbering_rule_id',
            'ext2' => 'HAA_Numbering_Rule',
            'module' => 'HAA_Numbering_Rule',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            ),
        'owning_person_rule' => 
        array (
            'required' => true,
            'name' => 'owning_person_rule',
            'vname' => 'LBL_OWNING_PERSON_RULE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '2',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'haa_frameworks_contact_rule',
            'studio' => 'visible',
            'dependency' => false,
            ),
        'using_person_rule' => 
        array (
            'required' => true,
            'name' => 'using_person_rule',
            'vname' => 'LBL_USING_PERSON_RULE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '2',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'haa_frameworks_contact_rule',
            'studio' => 'visible',
            'dependency' => false,
            ),
        'using_person_field_rule' => 
        array (
            'required' => true,
            'name' => 'using_person_field_rule',
            'vname' => 'LBL_USING_PERSON_FIELD_RULE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '2',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'haa_frameworks_field_rule',
            'studio' => 'visible',
            'dependency' => false,
            ),
        'owning_person_field_rule' => 
        array (
            'required' => true,
            'name' => 'owning_person_field_rule',
            'vname' => 'LBL_OWNING_PERSON_FIELD_RULE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '2',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'haa_frameworks_field_rule',
            'studio' => 'visible',
            'dependency' => false,
            ),
        'sales_person_field_rule' => 
        array (
            'required' => true,
            'name' => 'sales_person_field_rule',
            'vname' => 'LBL_SALES_PERSON_FIELD_RULE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '2',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'haa_frameworks_field_rule',
            'studio' => 'visible',
            'dependency' => false,
            ),
        'service_person_field_rule' => 
        array (
            'required' => true,
            'name' => 'service_person_field_rule',
            'vname' => 'LBL_SERVICE_PERSON_FIELD_RULE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '2',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'haa_frameworks_field_rule',
            'studio' => 'visible',
            'dependency' => false,
            ),
        'supplier_field_rule' => 
        array (
            'required' => true,
            'name' => 'supplier_field_rule',
            'vname' => 'LBL_SUPPLIER_FIELD_RULE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '2',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'haa_frameworks_field_rule',
            'studio' => 'visible',
            'dependency' => false,
            ),
        'source_reference_field_rule' => 
        array (
            'required' => true,
            'name' => 'source_reference_field_rule',
            'vname' => 'LBL_SOURCE_REFERENCE_FIELD_RULE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '2',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'haa_frameworks_field_rule',
            'studio' => 'visible',
            'dependency' => false,
            ),

        'location_display_rule' => 
        array (
            'required' => true,
            'name' => 'location_display_rule',
            'vname' => 'LBL_LOCATION_DISPLAY_RULE',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'haa_frameworks_display_rule',
            'studio' => 'visible',
            'dependency' => false,
            ),
        'asset_display_rule' => 
        array (
            'required' => true,
            'name' => 'asset_display_rule',
            'vname' => 'LBL_ASSET_DISPLAY_RULE',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'haa_frameworks_display_rule',
            'studio' => 'visible',
            'dependency' => false,
            ),
        'itrack_aos_products_id' =>
        array (
          'inline_edit' => 1,
          'required' => false,
      //'source' => 'custom_fields',
          'name' => 'itrack_aos_products_id',
          'vname' => 'LBL_ITRACK_ASSET_GROUP_ID',
          'type' => 'id',
          'massupdate' => '0',
          'default' => NULL,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => false,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '36',
          'size' => '20',
          ),
        'itrack_asset_group' =>
        array (
          'inline_edit' => '1',
          'labelValue' => 'Product/Asset Group',
          'required' => false,
          'source' => 'non-db',
          'name' => 'itrack_asset_group',
          'vname' => 'LBL_ITRACK_ASSET_GROUP',
          'type' => 'relate',
          'massupdate' => '0',
          'default' => NULL,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
          'id_name' => 'itrack_aos_products_id',
          'ext2' => 'AOS_Products',
          'module' => 'AOS_Products',
          'rname' => 'name',
          'quicksearch' => 'enabled',
          'studio' => 'visible',
          'id' => 'itrack_aos_products_id',
      //'custom_module' => 'HAT_Assets',
          ),
        'logo_image' =>
        array(
            'name' => 'logo_image',
            'vname' => 'LBL_LOGO_IMAGE',
            'type' => 'image',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 255,
            'size' => '20',
            'studio' => 'visible',
            'dbType' => 'varchar',
            'border' => '',
            'width' => '500',
            'height' => '',
            ),
        'file_url' =>
        array(
            'name' => 'file_url',
            'vname' => 'LBL_FILE_URL',
            'type' => 'function',
            'function_require' => 'include/upload_file.php',
            'function_class' => 'UploadFile',
            'function_name' => 'get_url',
            'function_params' => array('filename', 'id'),
            'source' => 'function',
            'reportable' => false,
            'comment' => 'Path to file (can be URL)'
            ),
        ),
'relationships'=>array (

 ),
'optimistic_locking'=>true,
'unified_search'=>true,
);
if (!class_exists('VardefManager')){
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('HAA_Frameworks','HAA_Frameworks', array('basic','assignable','security_groups'));
//VardefManager::createVardef('HAA_Frameworks','HAA_Frameworks', array('basic','assignable'));