<?php
$dictionary['HAM_WOOP'] = array (
	'table' => 'ham_woop',
	'audited' => true,
	'inline_edit' => true,
	'duplicate_merge' => true,
	'fields' => array (

		'ham_wo_id' => array (
			'required' => false,
			'name' => 'ham_wo_id',
			'vname' => 'LBL_WO_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
		),
		'wo_number' =>
		array (
			'inline_edit' => '',
			'required' => true,
			'source' => 'non-db',
			'name' => 'wo_number',
			'vname' => 'LBL_WO_NUMBER',
			'type' => 'relate',
			'massupdate' => '0',
			'default' => NULL,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => false,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'ham_wo_id',
			'ext2' => 'HAM_WO',
			'module' => 'HAM_WO',
			'rname' => 'wo_number',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			'id' => 'ham_wo_id',
			),
		'woop_number' => array (
			'required' => false,
			'name' => 'woop_number',
			'vname' => 'LBL_WOOP_NUMBER',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
		),
		'date_target_start' => array (
			'required' => true,
			'name' => 'date_target_start',
			'vname' => 'LBL_TARGET_START_DATE',
			'type' => 'datetimecombo',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'size' => '20',
			'enable_range_search' => false,
			'dbType' => 'datetime',
			//'display_default' => 'now&12:00am',
		),
		'date_target_finish' => array (
			'required' => true,
			'name' => 'date_target_finish',
			'vname' => 'LBL_TARGET_FINISH_DATE',
			'type' => 'datetimecombo',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'size' => '20',
			'enable_range_search' => false,
			'dbType' => 'datetime',
			// 'display_default' => 'now&12:00am',
		),
		'date_actual_start' => array (
			'required' => false,
			'name' => 'date_actual_start',
			'vname' => 'LBL_ACTUAL_START_DATE',
			'type' => 'datetimecombo',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'size' => '20',
			'enable_range_search' => false,
			'dbType' => 'datetime',
			// 'display_default' => 'now&12:00am',
		),
		'date_actual_finish' => array (
			'required' => false,
			'name' => 'date_actual_finish',
			'vname' => 'LBL_ACTUAL_FINISH_DATE',
			'type' => 'datetimecombo',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'size' => '20',
			'enable_range_search' => false,
			'dbType' => 'datetime',
			// 'display_default' => 'now&12:00am',

	
		),
		'date_schedualed_start' => array (
			'required' => false,
			'name' => 'date_schedualed_start',
			'vname' => 'LBL_SCHEDUALED_START_DATE',
			'type' => 'datetimecombo',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'size' => '20',
			'enable_range_search' => false,
			'dbType' => 'datetime',
			// 'display_default' => 'now&12:00am',

	
		),
		'date_schedualed_finish' => array (
			'required' => false,
			'name' => 'date_schedualed_finish',
			'vname' => 'LBL_SCHEDUALED_FINISH_DATE',
			'type' => 'datetimecombo',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'size' => '20',
			'enable_range_search' => false,
			'dbType' => 'datetime',
			// 'display_default' => 'now&12:00am',

	
		),
		'date_start_not_earlier' => array (
			'required' => false,
			'name' => 'date_start_not_earlier',
			'vname' => 'LBL_START_NOT_EARLIER_DATE',
			'type' => 'datetimecombo',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'size' => '20',
			'enable_range_search' => false,
			'dbType' => 'datetime',
			// 'display_default' => 'now&12:00am',

	
		),
		'date_finish_not_later' => array (
			'required' => false,
			'name' => 'date_finish_not_later',
			'vname' => 'LBL_FINISH_NOT_LATER_DATE',
			'type' => 'datetimecombo',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'size' => '20',
			'enable_range_search' => false,
			'dbType' => 'datetime',
			// 'display_default' => 'now&12:00am',

	
		),
		'woop_status' => array (
			'required' => true,
			'name' => 'woop_status',
			'vname' => 'LBL_WOOP_STATUS',
			'type' => 'enum',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 100,
			'size' => '20',
			'options' => 'ham_wo_status_list',
			'studio' => 'visible',
			'dependency' => false,
		),
		'woop_status_tagged' => array (
			'required' => true,
			'name' => 'woop_status_tagged',
			'vname' => 'LBL_WOOP_STATUS',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'source' => 'non-de',
		),
		'ham_work_center_id' => array (
			'required' => true,
			'name' => 'ham_work_center_id',
			'vname' => 'LBL_WORK_CENTER_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',

			
		),
		'work_center' => array (
			'required' => true,
			'source' => 'non-db',
			'name' => 'work_center',
			'vname' => 'LBL_WORK_CENTER',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'ham_work_center_id',
			'ext2' => 'HAM_Work_Centers',
			'module' => 'HAM_Work_Centers',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',

			
		),
		'contact_id' => array (
			'required' => false,
			'name' => 'contact_id',
			'vname' => 'LBL_OWNER_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',

		),
		'owner' => array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'owner',
			'vname' => 'LBL_OWNER',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'contact_id',
			'ext2' => 'Contacts',
			'module' => 'Contacts',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',

		),

		'work_center_res_id' => array (
			'required' => true,
			'name' => 'work_center_res_id',
			'vname' => 'LBL_WORK_CENTER_RES_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',

		),

		'work_center_res' => array (
			'required' => true,
			'source' => 'non-db',
			'name' => 'work_center_res',
			'vname' => 'LBL_WORK_CENTER_RES',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'work_center_res_id',
			'ext2' => 'HAM_Work_Center_Res',
			'module' => 'HAM_Work_Center_Res',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',

		),

		'work_center_people_id' => array (
			'required' => false,
			'name' => 'work_center_people_id',
			'vname' => 'LBL_WORK_CENTER_PEOPLE_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
		),

		'work_center_people' => array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'work_center_people',
			'vname' => 'LBL_HAM_WORK_CENTER_PEOPLE',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'work_center_people_id',
			'ext2' => 'HAM_Work_Center_People',
			'module' => 'HAM_Work_Center_People',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',

			
		),
		#目标时长：小时
	'duration_target' => array (
			'required' => false,
			'name' => 'duration_target',
			'vname' => 'LBL_DURATION_TARGET',
			'type' => 'decimal',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '18',
			'size' => '20',
			'enable_range_search' => false,
			'precision' => '8',

			
		),
		#计划时长：小时
	'duration_schedualed' => array (
			'required' => false,
			'name' => 'duration_schedualed',
			'vname' => 'LBL_DURATION_SCHEDUALED',
			'type' => 'decimal',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '18',
			'size' => '20',
			'enable_range_search' => false,
			'precision' => '8',

			
		),
		#实际时长：小时  
	'duration_actual' => array (
			'required' => false,
			'name' => 'duration_actual',
			'vname' => 'LBL_DURATION_ACTUAL',
			'type' => 'decimal',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '18',
			'size' => '20',
			'enable_range_search' => false,
			'precision' => '8',
		),

		'act_module' => array (
			'required' => false,
			'name' => 'act_module',
			'vname' => 'LBL_ACT_MODULE',
			'type' => 'enum',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 100,
			'size' => '20',
			'options' => 'ham_woop_moduleList',
			'studio' => 'visible',
			'dependency' => false,

		),
        'hat_eventtype_id' => 
        array (
          'required' => false,
          'name' => 'hat_eventtype_id',
          'vname' => 'LBL_HAT_EVENTTYPE_ID',
          'type' => 'id',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => 0,
          'audited' => false,
          'inline_edit' => true,
          'reportable' => false,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => 36,
          'size' => '20',
          ),
        'event_type' => 
        array (
          'required' => false,
          'source' => 'non-db',
          'name' => 'event_type',
          'vname' => 'LBL_EVENT_TYPE',
          'type' => 'relate',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'inline_edit' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
          'id_name' => 'hat_eventtype_id',
          'ext2' => 'HAT_EventType',
          'module' => 'HAT_EventType',
          'rname' => 'name',
          'quicksearch' => 'enabled',
          'studio' => 'visible',
          ),
		#序号     
	'next_woop' => array (
			'source' => 'non-db', //显示当前地点的说明
	'name' => 'next_woop',
			'vname' => 'LBL_NEXT_WOOP',
			'type' => 'varchar',
			'default' => '',
			'reportable' => true,
			'studio' => 'visible'
		),

		#后序任务
	'next_woop_name' => array (
			'source' => 'non-db', //显示当前地点的说明
	'name' => 'next_woop_name',
			'vname' => 'LBL_NEXT_WOOP_NAME',
			'type' => 'varchar',
			'default' => '',
			'reportable' => true,
			'studio' => 'visible'
		),

		#工作中心
	'next_work_center' => array (
			'source' => 'non-db', //显示当前地点的说明
	'name' => 'next_work_center',
			'vname' => 'LBL_NEXT_WORK_CENTER',
			'type' => 'varchar',
			'default' => '',
			'reportable' => true,
			'studio' => 'visible'
		),

		'next_work_center_res_id' => array (
			'required' => false,
			'name' => 'next_work_center_res_id',
			'vname' => 'LBL_NEXT_WORK_CENTER_RES_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',

			
		),

		'next_work_center_res' => array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'next_work_center_res',
			'vname' => 'LBL_NEXT_WORK_CENTER_RES',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'next_work_center_res_id', //返回的值 显示name存储id
	'ext2' => 'HAM_Work_Center_Res',
			'module' => 'HAM_Work_Center_Res',
			'rname' => 'name', //在界面上面显示其他模块的 HAT_Assets的Name字段 也就是前台显示
	'quicksearch' => 'enabled',
			'studio' => 'visible',

			
		),

		'next_work_center_people_id' => array (
			'required' => false,
			'name' => 'next_work_center_people_id',
			'vname' => 'LBL_NEXT_WORK_CENTER_PEOPLE_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',

			
		),

		'next_work_center_people' => array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'next_work_center_people',
			'vname' => 'LBL_NEXT_WORK_CENTER_PEOPLE',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'next_work_center_people_id', //返回的值 显示name存储id
	'ext2' => 'HAM_Work_Center_People',
			'module' => 'HAM_Work_Center_People',
			'rname' => 'name', //在界面上面显示其他模块的 HAT_Assets的Name字段 也就是前台显示
	'quicksearch' => 'enabled',
			'studio' => 'visible',

			
		),

		#完工后打开下道工序
	'autoopen_next_task' => array (
			'required' => false,
			'name' => 'autoopen_next_task',
			'vname' => 'LBL_AUTOOPEN_NEXT_TASK',
			'type' => 'bool',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => false,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			
		),
		
		#同步工单状态
	'syn_wo_status' => array (
			'required' => false,
			'name' => 'syn_wo_status',
			'vname' => 'LBL_SYN_WO_STATUS',
			'type' => 'bool',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => false,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			
		),

		#认领工单
	'woop_action' => array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'woop_action',
			'vname' => 'LBL_WOOP_ACTION',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
	'quicksearch' => 'enabled',
			'studio' => 'visible',	
		),
		
		
		#合同号
	'contract_id' => array (
			'required' => false,
			'name' => 'contract_id',
			'vname' => 'LBL_CONTRACT_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',

			
		),
		'contract' => array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'contract',
			'vname' => 'LBL_CONTRACT',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'contract_id',
			'ext2' => 'AOS_Contracts',
			'module' => 'AOS_Contracts',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',

			
		),

		
	),
	'relationships' => array (),
	'optimistic_locking' => true,
	'unified_search' => true,

	
);
if (!class_exists('VardefManager')) {
	require_once ('include/SugarObjects/VardefManager.php');
}
VardefManager :: createVardef('HAM_WOOP', 'HAM_WOOP', array (
	'basic',
	'assignable',
	'security_groups'
));