<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/

$dictionary['HFA_Fixed_Assets'] = array(
	'table'=>'hfa_fixed_assets',
	'audited'=>true,
	'inline_edit'=>true,
	'duplicate_merge'=>true,
	'fields'=>array (
		'haa_frameworks_id' => 
		array (
			'required' => false,
			'name' => 'haa_frameworks_id',
			'vname' => 'LBL_HAA_FRAMEWORKS_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'haa_framework' => 
		array (
			'required' => true,
			'source' => 'non-db',
			'name' => 'haa_framework',
			'vname' => 'LBL_HAA_FRAMEWORK',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => true,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'haa_frameworks_id',
			'ext2' => 'HAA_Frameworks',
			'module' => 'HAA_Frameworks',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'owning_dept' => 
		array (
			'required' => false,
			'name' => 'owning_dept',
			'vname' => 'LBL_OWNING_DEPT',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			),
		'location' => 
		array (
			'required' => false,
			'name' => 'location',
			'vname' => 'LBL_LOCATION',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			),
		'original_value' => 
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'original_value',
			'vname' => 'LBL_ORIGINAL_VALUE',
			'type' => 'currency',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 26,
			'size' => '20',
			'enable_range_search' => false,
			'precision' => 6,
			),
		'currency_id' => 
		array (
			'required' => false,
			'name' => 'currency_id',
			'vname' => 'LBL_CURRENCY',
			'type' => 'currency_id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			'dbType' => 'id',
			'studio' => 'visible',
			'function' => 
			array (
				'name' => 'getCurrencyDropDown',
				'returns' => 'html',
				),
			),
		'current_value' => 
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'current_value',
			'vname' => 'LBL_CURRENT_VALUE',
			'type' => 'currency',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 26,
			'size' => '20',
			'enable_range_search' => false,
			'precision' => 6,
			),
		'ytd_depre' => 
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'ytd_depre',
			'vname' => 'LBL_YTD_DEPRE',
			'type' => 'currency',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 26,
			'size' => '20',
			'enable_range_search' => false,
			'precision' => 6,
			),
		'accumulated_depre' => 
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'accumulated_depre',
			'vname' => 'LBL_ACCUMULATED_DEPRE',
			'type' => 'currency',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 26,
			'size' => '20',
			'enable_range_search' => false,
			'precision' => 6,
			),
		'net_value' => 
		array (
			'required' => false,
			'name' => 'net_value',
			'vname' => 'LBL_NET_VALUE',
			'type' => 'currency',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 26,
			'size' => '20',
			'enable_range_search' => false,
			'precision' => 6,
			),
		'recoverable_amount' => 
		array (
			'required' => false,
			'name' => 'recoverable_amount',
			'vname' => 'LBL_RECOVERABLE_AMOUNT',
			'type' => 'currency',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 26,
			'size' => '20',
			'enable_range_search' => false,
			'precision' => 6,
			),
		'salvage_value' => 
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'salvage_value',
			'vname' => 'LBL_SALVAGE_VALUE',
			'type' => 'currency',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 26,
			'size' => '20',
			'enable_range_search' => false,
			'precision' => 6,
			),
		'depreciation_prep' => 
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'depreciation_prep',
			'vname' => 'LBL_DEPRECIATION_PREP',
			'type' => 'currency',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 26,
			'size' => '20',
			'enable_range_search' => false,
			'precision' => 6,
			),
		'fixed_asset_type' => 
		array (
			'required' => false,
			'name' => 'fixed_asset_type',
			'vname' => 'LBL_FIXED_ASSET_TYPE',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 100,
			'size' => '20',
			'options' => 'fixed_asset_type_list',
			'studio' => 'visible',
			'dependency' => false,
			),
		'date_in_service' => 
		array (
			'required' => false,
			'name' => 'date_in_service',
			'vname' => 'LBL_DATE_IN_SERVICE',
			'type' => 'date',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'size' => '20',
			'enable_range_search' => false,
			),
		'service_year' => 
		array (
			'required' => false,
			'name' => 'service_year',
			'vname' => 'LBL_SERVICE_YEAR',
			'type' => 'decimal',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '18',
			'size' => '20',
			'enable_range_search' => false,
			'precision' => '1',
			),
		'book_name' => 
		array (
			'required' => false,
			'name' => 'book_name',
			'vname' => 'LBL_BOOK_NAME',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 100,
			'size' => '20',
			'options' => 'book_name_list',
			'studio' => 'visible',
			'dependency' => false,
			),
		'fa_value_link' =>
		array(
			'name' => 'fa_value_link',
			'type' => 'link',
			'relationship' => 'hfa_fa_value',
			'vname' => 'LBL_FAVALUE_SUBPANEL_TITLE',
			'link_type' => 'many',
			'module' => 'HFA_FA_Value',
			'bean_name' => 'HFA_FA_Value',
			'source' => 'non-db',
			),
		),

'relationships'=>array (
	
	'hfa_fa_value' =>
	array (
		'lhs_module' => 'HFA_Fixed_Assets',
		'lhs_table' => 'hfa_fixed_assets',
		'lhs_key'   => 'id',
		'rhs_module' => 'HFA_FA_Value',
		'rhs_table' => 'hfa_fa_value',
		'rhs_key'   => 'hfa_fixed_assets_id',
		'relationship_type' => 'one-to-many',
		),
	),

'optimistic_locking'=>true,
'unified_search'=>true,
);
if (!class_exists('VardefManager')){
	require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('HFA_Fixed_Assets','HFA_Fixed_Assets', array('basic','assignable','security_groups'));