<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/

$dictionary['HAA_Integration_Interface_Headers'] = array(
	'table'=>'haa_integration_interface_headers',
	'audited'=>true,
	'inline_edit'=>true,
	'duplicate_merge'=>true,
	'fields'=>array (
		'haa_frameworks_id_c' => 
		array (
			'required' => false,
			'name' => 'haa_frameworks_id_c',
			'vname' => 'LBL_FRAMEWORKS_HAA_FRAMEWORKS_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'frameworks' => 
		array (
			'required' => true,
			'source' => 'non-db',
			'name' => 'frameworks',
			'vname' => 'LBL_FRAMEWORKS',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'haa_frameworks_id_c',
			'ext2' => 'HAA_Frameworks',
			'module' => 'HAA_Frameworks',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'haa_interfaces_id_c' => 
		array (
			'required' => false,
			'name' => 'haa_interfaces_id_c',
			'vname' => 'LBL_OWN_INTERFACE_HAA_INTERFACES_ID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'inline_edit' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 36,
			'size' => '20',
			),
		'own_interface' => 
		array (
			'required' => true,
			'source' => 'non-db',
			'name' => 'own_interface',
			'vname' => 'LBL_OWN_INTERFACE',
			'type' => 'relate',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			'id_name' => 'haa_interfaces_id_c',
			'ext2' => 'HAA_Interfaces',
			'module' => 'HAA_Interfaces',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			),
		'interface_code' => 
		array (
			'required' => true,
			'name' => 'interface_code',
			'vname' => 'LBL_INTERFACE_CODE',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			),
		'ext_batch_number' => 
		array (
			'name' => 'ext_batch_number',
			'vname' => 'LBL_EXT_BATCH_NUMBER',
			'type' => 'name',
			'link' => true,
			'dbType' => 'varchar',
			'len' => '255',
			'unified_search' => false,
			'full_text_search' => 
			array (
				'boost' => 3,
				),
			'required' => true,
			'importable' => 'required',
			'duplicate_merge' => 'disabled',
			'merge_filter' => 'disabled',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'size' => '20',
			),
		'received_date' => 
		array (
			'required' => true,
			'name' => 'received_date',
			'vname' => 'LBL_RECEIVED_DATE',
			'dbType' => 'datetime',
			'type' => 'datetimecombo',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => '',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'size' => '20',
			'enable_range_search' => true,
    		'options' => 'date_range_search_dom',
			),
		'line_cnt' => 
		array (
			'required' => false,
			'name' => 'line_cnt',
			'vname' => 'LBL_LINE_CNT',
			'type' => 'int',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
			),
		'process_status' => 
		array (
			'required' => true,
			'name' => 'process_status',
			'vname' => 'LBL_PROCESS_STATUS',
			'type' => 'enum',
			'massupdate' => 0,
			'default' => '',
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => '',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => 100,
			'size' => '20',
			'options' => 'haa_integration_process_status',
			'studio' => 'visible',
			'dependency' => false,
			),
		'process_date' => 
		array (
			'required' => false,
			'name' => 'process_date',
			'vname' => 'LBL_PROCESS_DATE',
			'dbType' => 'datetime',
			'type' => 'datetimecombo',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => '',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'size' => '20',
			'enable_range_search' => false,
			),
		'process_message' => 
		array (
			'required' => false,
			'name' => 'process_message',
			'vname' => 'LBL_PROCESS_MESSAGE',
			'type' => 'text',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '2000',
			'size' => '20',
			),
		'execute_file' => 
		array (
			'required' => false,
			'name' => 'execute_file',
			'vname' => 'LBL_EXECUTE_FILE',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '2000',
			'size' => '20',
			),
		'reference1' => 
		array (
			'required' => false,
			'name' => 'reference1',
			'vname' => 'LBL_REFERENCE1',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '600',
			'size' => '20',
			),
		'reference2' => 
		array (
			'required' => false,
			'name' => 'reference2',
			'vname' => 'LBL_REFERENCE2',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '600',
			'size' => '20',
			),
		'reference3' => 
		array (
			'required' => false,
			'name' => 'reference3',
			'vname' => 'LBL_REFERENCE3',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '600',
			'size' => '20',
			),
		'reference4' => 
		array (
			'required' => false,
			'name' => 'reference4',
			'vname' => 'LBL_REFERENCE4',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '600',
			'size' => '20',
			),
		'description' => 
		array (
			'name' => 'description',
			'vname' => 'LBL_DESCRIPTION',
			'type' => 'text',
			'comment' => 'Full text of the note',
			'rows' => '6',
			'cols' => '80',
			'required' => false,
			'massupdate' => 0,
			'no_default' => false,
			'comments' => 'Full text of the note',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'size' => '20',
			'studio' => 'visible',
			),
		'line_items' =>
		array(
			'required' => false,
			'name' => 'line_items',
			'vname' => 'LBL_LINE_ITEMS',
			'type' => 'function',
			'source' => 'non-db',
			'massupdate' => 0,
			'importable' => 'false',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'reportable' => false,
			'function' =>
			array(
				'name' => 'display_lines',
				'returns' => 'html',
				'include' => 'modules/HAA_Integration_Interface_Lines/Line_Items.php'
				),
			),
		'line_infos' =>
		array(
			'required' => false,
			'name' => 'line_infos',
			'vname' => 'LBL_LINE_INFOS',
			'type' => 'function',
			'source' => 'non-db',
			'massupdate' => 0,
			'importable' => 'false',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'reportable' => false,
			'function' =>
			array(
				'name' => 'display_lines_info',
				'returns' => 'html',
				'include' => 'modules/HAA_Integration_Interface_Lines/Line_Infos.php'
				),
			),
		),
'relationships'=>array (
	),
'optimistic_locking'=>true,
'unified_search'=>true,
);
if (!class_exists('VardefManager')){
	require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('HAA_Integration_Interface_Headers','HAA_Integration_Interface_Headers', array('basic','assignable','security_groups'));
