INSERT INTO `suitecrm`.`haa_codes` (`id`, `name`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `description`, `deleted`, `assigned_user_id`, `code_type`, `haa_ff_id`, `code_tag`) VALUES ('4c706a90-8b1e-cb53-c5d2-5805efa7fb8c', '面试', '2016-10-18 09:45:31', '2016-10-19 03:29:38', '1', '1', '任务：面试', '0', '', 'task_type', '91d703fb-985a-e27d-f01c-5806e8f4d329', NULL);
INSERT INTO `suitecrm`.`haa_codes` (`id`, `name`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `description`, `deleted`, `assigned_user_id`, `code_type`, `haa_ff_id`, `code_tag`) VALUES ('c7ac5351-fbe7-c904-787c-5805efbca506', '签约', '2016-10-18 09:46:19', '2016-10-18 09:46:19', '1', '1', '', '0', NULL, 'task_type', '', '');

INSERT INTO `suitecrm`.`fields_meta_data` (`id`, `name`, `vname`, `comments`, `help`, `custom_module`, `type`, `len`, `required`, `default_value`, `date_modified`, `deleted`, `audited`, `massupdate`, `duplicate_merge`, `reportable`, `importable`, `ext1`, `ext2`, `ext3`, `ext4`) VALUES ('Tasksattribute2_c', 'attribute2_c', 'LBL_ATTRIBUTE2', '', '', 'Tasks', 'varchar', '255', '0', '', '2016-10-18 08:50:46', '0', '0', '0', '0', '1', 'true', '', '', '', '');
INSERT INTO `suitecrm`.`fields_meta_data` (`id`, `name`, `vname`, `comments`, `help`, `custom_module`, `type`, `len`, `required`, `default_value`, `date_modified`, `deleted`, `audited`, `massupdate`, `duplicate_merge`, `reportable`, `importable`, `ext1`, `ext2`, `ext3`, `ext4`) VALUES ('Tasksattribute1_c', 'attribute1_c', 'LBL_ATTRIBUTE1', '', '', 'Tasks', 'varchar', '255', '0', '', '2016-10-18 08:45:56', '0', '0', '0', '0', '1', 'true', '', '', '', '');
INSERT INTO `suitecrm`.`fields_meta_data` (`id`, `name`, `vname`, `comments`, `help`, `custom_module`, `type`, `len`, `required`, `default_value`, `date_modified`, `deleted`, `audited`, `massupdate`, `duplicate_merge`, `reportable`, `importable`, `ext1`, `ext2`, `ext3`, `ext4`) VALUES ('Tasksattribute3_c', 'attribute3_c', 'LBL_ATTRIBUTE3', '', '', 'Tasks', 'varchar', '255', '0', '', '2016-10-18 08:51:37', '0', '0', '0', '0', '1', 'true', '', '', '', '');
INSERT INTO `suitecrm`.`fields_meta_data` (`id`, `name`, `vname`, `comments`, `help`, `custom_module`, `type`, `len`, `required`, `default_value`, `date_modified`, `deleted`, `audited`, `massupdate`, `duplicate_merge`, `reportable`, `importable`, `ext1`, `ext2`, `ext3`, `ext4`) VALUES ('Tasksattribute4_c', 'attribute4_c', 'LBL_ATTRIBUTE4', '', '', 'Tasks', 'varchar', '255', '0', '', '2016-10-18 08:52:13', '0', '0', '0', '0', '1', 'true', '', '', '', '');
INSERT INTO `suitecrm`.`fields_meta_data` (`id`, `name`, `vname`, `comments`, `help`, `custom_module`, `type`, `len`, `required`, `default_value`, `date_modified`, `deleted`, `audited`, `massupdate`, `duplicate_merge`, `reportable`, `importable`, `ext1`, `ext2`, `ext3`, `ext4`) VALUES ('Tasksattribute5_c', 'attribute5_c', 'LBL_ATTRIBUTE5', '', '', 'Tasks', 'varchar', '255', '0', '', '2016-10-18 08:53:07', '0', '0', '0', '0', '1', 'true', '', '', '', '');
INSERT INTO `suitecrm`.`fields_meta_data` (`id`, `name`, `vname`, `comments`, `help`, `custom_module`, `type`, `len`, `required`, `default_value`, `date_modified`, `deleted`, `audited`, `massupdate`, `duplicate_merge`, `reportable`, `importable`, `ext1`, `ext2`, `ext3`, `ext4`) VALUES ('Tasksattribute6_c', 'attribute6_c', 'LBL_ATTRIBUTE6', '', '', 'Tasks', 'varchar', '255', '0', '', '2016-10-18 08:53:46', '0', '0', '0', '0', '1', 'true', '', '', '', '');
INSERT INTO `suitecrm`.`fields_meta_data` (`id`, `name`, `vname`, `comments`, `help`, `custom_module`, `type`, `len`, `required`, `default_value`, `date_modified`, `deleted`, `audited`, `massupdate`, `duplicate_merge`, `reportable`, `importable`, `ext1`, `ext2`, `ext3`, `ext4`) VALUES ('Tasksattribute7_c', 'attribute7_c', 'LBL_ATTRIBUTE7', '', '', 'Tasks', 'varchar', '255', '0', '', '2016-10-18 08:54:24', '0', '0', '0', '0', '1', 'true', '', '', '', '');
INSERT INTO `suitecrm`.`fields_meta_data` (`id`, `name`, `vname`, `comments`, `help`, `custom_module`, `type`, `len`, `required`, `default_value`, `date_modified`, `deleted`, `audited`, `massupdate`, `duplicate_merge`, `reportable`, `importable`, `ext1`, `ext2`, `ext3`, `ext4`) VALUES ('Tasksattribute8_c', 'attribute8_c', 'LBL_ATTRIBUTE8', '', '', 'Tasks', 'varchar', '255', '0', '', '2016-10-18 08:54:59', '0', '0', '0', '0', '1', 'true', '', '', '', '');
INSERT INTO `suitecrm`.`fields_meta_data` (`id`, `name`, `vname`, `comments`, `help`, `custom_module`, `type`, `len`, `required`, `default_value`, `date_modified`, `deleted`, `audited`, `massupdate`, `duplicate_merge`, `reportable`, `importable`, `ext1`, `ext2`, `ext3`, `ext4`) VALUES ('Taskstask_type_c', 'task_type_c', 'LBL_TASK_TYPE', NULL, NULL, 'Tasks', 'relate', '255', '1', NULL, '2016-10-19 04:58:55', '0', '0', '0', '0', '1', 'true', NULL, 'HAA_Codes', 'haa_codes_id_c', NULL);
INSERT INTO `suitecrm`.`fields_meta_data` (`id`, `name`, `vname`, `comments`, `help`, `custom_module`, `type`, `len`, `required`, `default_value`, `date_modified`, `deleted`, `audited`, `massupdate`, `duplicate_merge`, `reportable`, `importable`, `ext1`, `ext2`, `ext3`, `ext4`) VALUES ('Taskshaa_codes_id_c', 'haa_codes_id_c', 'LBL_TASK_TYPE_HAA_CODES_ID', '', '', 'Tasks', 'id', '36', '0', NULL, '2016-10-19 04:54:53', '0', '0', '0', '0', '0', 'true', '', '', '', '');
INSERT INTO `suitecrm`.`fields_meta_data` (`id`, `name`, `vname`, `comments`, `help`, `custom_module`, `type`, `len`, `required`, `default_value`, `date_modified`, `deleted`, `audited`, `massupdate`, `duplicate_merge`, `reportable`, `importable`, `ext1`, `ext2`, `ext3`, `ext4`) VALUES ('Taskshaa_framework_c', 'haa_framework_c', 'LBL_HAA_FRAMEWORK', '', '', 'Tasks', 'relate', '255', '1', NULL, '2016-10-20 03:40:01', '0', '0', '0', '0', '1', 'true', '', 'HAA_Frameworks', 'haa_frameworks_id_c', '');
INSERT INTO `suitecrm`.`fields_meta_data` (`id`, `name`, `vname`, `comments`, `help`, `custom_module`, `type`, `len`, `required`, `default_value`, `date_modified`, `deleted`, `audited`, `massupdate`, `duplicate_merge`, `reportable`, `importable`, `ext1`, `ext2`, `ext3`, `ext4`) VALUES ('Taskshaa_frameworks_id_c', 'haa_frameworks_id_c', 'LBL_HAA_FRAMEWORK_HAA_FRAMEWORKS_ID', '', '', 'Tasks', 'id', '36', '0', NULL, '2016-10-20 03:40:01', '0', '0', '0', '0', '0', 'true', '', '', '', '');
